### ISSUE TITLE
Updating YouTube Thumbnails

### ISSUE THREAD

**Issue by rileymiller** [LuanRT/YouTube.js#104]
### Describe your suggestion

Does anyone know if there's an innertube endpoint to update a video's thumbnail? One of the pains of livestreaming on YouTube is having to set a thumbnail each time you go live. It would be awesome if there was an endpoint to update the thumbnail so you could create a service that would dynamically update a livestreams thumbnail based on what's going on in the stream—similar to what Twitch does for their thumbnails.

### Other details

Ludwig talked about this in a video recently for more context: https://www.youtube.com/watch?v=qtY-rXi0-vQ

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hi @rileymiller, 

I was actually looking into this about a month ago and already know the endpoint used to do it (`/video_manager/metadata_update`). After analyzing the protobuf found in the YTStudio apk I managed to get it working and will be implementing it in the library after #97 & #93.
 
Thanks!

**Comment by rileymiller** [comment]
@LuanRT awesome! :)

**Comment by LuanRT** [comment]
See #111, works like a charm for videos but I haven't tried it on livestreams yet. Will do some more tests later.

**Comment by Wykerd** [comment]
Just tested, does indeed work on live streams: https://www.youtube.com/watch?v=6a70KaY5Dwo

**Comment by rileymiller** [comment]
Awesome!
