### ISSUE TITLE
stable There's `removeLike`, but no `removeDislike`.

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#107]
### Describe your suggestion

Just like `removeDislike`, but for a like.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Wykerd** [comment]
`removeLike` should remove either like or dislike. It appears as though there is a single https://www.youtube.com/youtubei/v1/like/removelike endpoint which handles both cases.

**Comment by MasterOfBob777** [comment]
Maybe though, add it as an alias and mention that in the jsdoc?

**Comment by Wykerd** [comment]
Another option could be to rename it `removeRating` instead?

**Comment by LuanRT** [comment]
> Another option could be to rename it `removeRating` instead?

I agree, let's just rename it.
