### ISSUE TITLE
Web bundle imports

### ISSUE THREAD

**Issue by Wykerd** [LuanRT/YouTube.js#108]
This issue is in reference to: https://github.com/LuanRT/YouTube.js/commit/6a5ebeb8eee980fb433016ae9269084cc57cc56e

There was a very specific reason for the `npx tsc --module esnext` command in the `bundle:general` script. ESBuild needed the compiled sources in esm format in order to generate the correct esm exports for the browser bundle.

By removing it you're left with this error:

![image](https://user-images.githubusercontent.com/45672955/180067798-4ed1dc46-5849-4793-b727-88ad28fbd7c9.png)

**Comment by LuanRT** [comment]
My bad😆
Should be fixed now.

**Comment by Wykerd** [comment]
Cool 👍
