### ISSUE TITLE
How to get the container format / file extension before starting stream?

### ISSUE THREAD

**Issue by ikmolbo** [LuanRT/YouTube.js#11]
Hi,

Looking at the example below, I want to download the best audio-only stream, but to pipe the stream to a file I need to know how to name that file. In your example, you hard-code an mp4 extension, but the actual container could be one of many  - we don't know until the info event is fired.

Is there a way to know the correct container of the file to be downloaded before starting the stream? 

One solution is to rename the file once the download is complete, but in my case I want to pipe the stream to an uploader, and need to know the file's extension before it starts.

```
const stream = youtube.download(search.videos[0].id, {
    type: 'audio' // can be “video”, “audio” and “videoandaudio”
  });
  
  stream.pipe(fs.createWriteStream(`./${search.videos[0].title}.mp4`)); // 'mp4' is hard-coded here, but this could be aac, webm, etc
```

**Comment by LuanRT** [comment]
Hello, 
The library chooses the highest quality audio by default. And regarding the file extension, it'll always be m4a as you can see here:
https://github.com/LuanRT/YouTube.js/blob/2b5027eb06a432bfb6a5c4f4a9f9e70ff0612c04/lib/Innertube.js#L404

YouTube does provide different audio formats but those are very low quality.

**Comment by ikmolbo** [comment]
That works - thank you (and for an excellent repo)!
