### ISSUE TITLE
bleeding-edge MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#118]
### Steps to reproduce

1. `mkdir demo; cd demo; npm init`
2. `npm install git+https://github.com/LuanRT/YouTube.js.git`
3. `cd ./node_modules/youtubei.js/examples/`
4. `node channel.js`

### Failure Logs

```shell
node:internal/modules/cjs/loader:367
      throw err;
      ^

Error: Cannot find module '/home/stas/Sync/Documents/yt-demo/node_modules/youtubei.js/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:359:19)
    at Module._findPath (node:internal/modules/cjs/loader:572:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:932:27)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/stas/Sync/Documents/yt-demo/node_modules/youtubei.js/examples/channel.js:1:19)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/stas/Sync/Documents/yt-demo/node_modules/youtubei.js/package.json',
  requestPath: '..'
}

Node.js v18.4.0
```

### Expected behavior

The example to run.

### Current behavior

A crash with `MODULE_NOT_FOUND`.

### Version

Edge

### Anything else?

Am I doing anything wrong?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by MasterOfBob777** [comment]
This is because you are installing from the github repo, you must now install via npm, i.e. `npm i youtubei.js`

**Comment by MasterOfBob777** [comment]
@LuanRT @Wykerd Should these files end up getting shipped with git?

**Comment by walking-octopus** [comment]
I'm trying to install the bleeding-edge version from GitHub for testing.

**Comment by Wykerd** [comment]
Before your step 3, run `cd ./node_modules/youtubei.js` then `npm run build`

**Comment by Wykerd** [comment]
Also note those examples are not kept up to date and may not work with all the new breaking changes being made currently.

**Comment by walking-octopus** [comment]
> Before your step 3, run `cd ./node_modules/youtubei.js` then `npm run build`

Thanks! The README doesn't currently mention it, so I didn't notice it.

**Comment by LuanRT** [comment]
> @LuanRT @Wykerd Should these files end up getting shipped with git.

Nope, it could simplify the installation for people using the edge version but having to update the build files every time we change something would be quite tiresome.
