### ISSUE TITLE
(V2) Is there any way to get *all* albums from an artist? 

### ISSUE THREAD

**Issue by titong0** [LuanRT/YouTube.js#139]
### Question

I am wondering if there's support for getting **all** albums from an artist in yt music. I was able to get the first 10 which do not require to press "MORE".
with 
```javascript
const artist = await client.music.getArtist("UCRY5dYsbIN5TylSbd7gVnZg");
// artist.sections[0] is popular songs, [1] is albums.
const albums = artist.sections[1].as(MusicCarouselShelf);

console.log(albums.contents); // MusicTwoRowItem array of length 10
```
I can get the browseId and params of the full albums list with the following snippet but I think they are used for low-level interactions.
```javascript
const artist = await client.music.getArtist("UCRY5dYsbIN5TylSbd7gVnZg");

const moreButton = albums.header?.more_content;

console.log(moreButton)

 // Button {
 //  type: 'Button',
 //  text: 'More',
 //  endpoint: NavigationEndpoint {
 //    type: 'NavigationEndpoint',
 //    payload: {
 //      browseId: 'UCPC0L1d253x-KuMNwa05TpA',
 //      params: '6gPkAUdxZ0JXcGtCQ3BZQkNpUjVkRjl3WVdkbFgzTnVZWEJ6YUc5MFgyMTFjMmxqWDNCaFoyVmZjbVZuYVc5dVlXd1NIM00yWWxjMk0weE5VR05WVW5kUFJVNTVTa1JmV0MwNFdrZGtjbVpMVW1jYVRRQUFaVzRBQVVGU0FBRkJVZ0FCQUVaRmJYVnphV05mWkdWMFlXbHNYMkZ5ZEdsemRBQUJBQUZEQUFBQkFBRUFBQUVCQUZWRFVFTXdUREZrTWpVemVDMUxkVTFPZDJFd05WUndRUUFCOHRxenFnb0dRQUZJQUZBaQ%3D%3D'
//      },
//   }
// }
```

### Other details

I am willing to implement this in case there's not already a way to do it

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Nope, not yet. But it's relatively easy for you to implement custom functionality — the “More” button you mentioned is clickable and you can call its endpoint to retrieve more items.

Ex:
```ts
const button = albums.as(MusicCarouselShelf).header?.more_content;
  
if (!button)
  throw new Error('“More” button not found');
    
const page = await button.endpoint.call(yt.actions, 'YTMUSIC', true);
  
const single_col = page?.contents.item().as(SingleColumnBrowseResults);
const grid = single_col?.tabs.firstOfType(Tab)?.content?.as(SectionList).contents.array().firstOfType(Grid);
 
console.info('Albums:\n', grid?.items.array());
```

**Comment by titong0** [comment]
Sorry, is this code snippet for library contribution or personal use case? because `SingleColumnBrowseResults`, `Tab`, `SectionList` and `Grid` are not defined so I'm guessing they are private types for internal libary usage.

**Comment by LuanRT** [comment]
> Sorry, is this code snippet for library contribution or personal use case? because `SingleColumnBrowseResults`, `Tab`, `SectionList` and `Grid` are not defined so I'm guessing they are private types for internal libary usage.

Those are individual parser types — you can simply import them.

```js
import Tab from './YouTube.js/dist/src/parser/classes/Tab';
import Grid from './YouTube.js/dist/src/parser/classes/Grid';
import Button from './YouTube.js/dist/src/parser/classes/Button';
import SectionList from './YouTube.js/dist/src/parser/classes/SectionList';
import SingleColumnBrowseResults from './YouTube.js/dist/src/parser/classes/SingleColumnBrowseResults';
import MusicCarouselShelf from './YouTube.js/dist/src/parser/classes/MusicCarouselShelf';

```

**Comment by titong0** [comment]
Oh sorry, I wasn't getting the autocomplete so I thought they weren't exposed with the library. Thanks so much! This might be useful in the new docs.

**Comment by titong0** [comment]
Hi there! Updated the library version and this solution no longer works. The problem seems to be in the line
```javascript
const page = await button.endpoint.call(client.actions, 'YTMUSIC', true);```

the variable `page` is filled with null values. I'd love to understand any of what's going on but it seems like a low level interaction with innertube. Thanks in advance!

**Comment by LuanRT** [comment]
Can you post the contents of the `page`? Maybe the structure of the response changed, but I doubt it.

Here's what you could try:

Update to v2.3.3, and change that line to this:
```ts
const page = await button.endpoint.call(client.actions, { parse: true, client: 'YTMUSIC' });
```
