### ISSUE TITLE
About range option

### ISSUE THREAD

**Issue by darahask** [LuanRT/YouTube.js#15]
## Question

- What exactly does range option in download function do? does it  seek? is range in seconds?

**Comment by LuanRT** [comment]
Hello, 

The range option is meant to be used to support partial downloads. 

Ah and it takes bytes as parameters:
```js
{ start: 0, end:  1048576 * 10 /* 10MB */ }
```

**Comment by darahask** [comment]
@LuanRT okay 👍. What is the output format of the download function?  Is the audio opus?

**Comment by LuanRT** [comment]
> @LuanRT okay 👍. What is the output format of the download function? Is the audio opus?

The default format is ``m4a``. However, YouTube does provide ``opus``, only downside is that it stores it in the ``webm`` format.

**Comment by darahask** [comment]
Okay thanks, great library by the way, the output audio quality is very good
