### ISSUE TITLE
1.3.6 Audio-only downloads are not compatible with Safari (OSX) and iOS

### ISSUE THREAD

**Issue by ikmolbo** [LuanRT/YouTube.js#16]
## Expected Behavior

A downloaded or streamed audio file (M4A/MP4) should play with the correct track length in all browsers and media players.

## Current Behavior

A downloaded or streamed audio file in MP4/M4A format plays as expected in Firefox/Chrome (OSX). However, in Quicktime and Safari (OSX) and on iOS (PocketCasts podcast player, Apple Podcasts, Safari iOS) the audio file will report a track length approximately double its real length. For example, a 1 minute track is shown as a 2 minute track on these problematic platforms. As a result, the track can finished at 50% and the remaining 50% is silence. 

This bug appears to be a result of some incompatibility between the DASH format of the MP4 file and Quicktime. The problem can be corrected using FFMEG to copy the file to a new MP4 container (non-DASH). `ffmpeg -i input.m4a  -c:a copy output.m4a`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Download the best audio-only file, e.g. `youtube.download("rVb6bGgyIrE", { type: 'audio' }); `
2. Open the downloaded file in Quicktime, Safari, iPhone, etc.
3. Notice that the reported track length is double what it should be.
4. Using FFMPEG, run the following command: `ffmpeg -i input.m4a  -c:a copy output.m4a`
5. Confirm that the output file now plays with the correct track length.

## My question

I've provided a solution for this (which is, I think, why other libraries use FFMPEG at the end of the download process), however is there any way to get working audio without FFMPEG? I'm building something in JS only, and needing to introduce FFMPEG here complicates things!

## Checklist

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x ] I have provided sufficient information

**Comment by LuanRT** [comment]
Hello,

This happens because the m4as provided by YouTube aren't quite compatible with some platforms (see [this](https://github.com/ytdl-org/youtube-dl/issues/5048#issuecomment-75733238)). Unfortunate, there doesn't seem to be any way to fix this other than using ffmpeg. 

However, YouTube provides other audio formats such as webm (opus). You could give them a try, unless they're not viable for your project.

**Comment by ikmolbo** [comment]
Thanks!
