### ISSUE TITLE
node:internal/errors:464

### ISSUE THREAD

**Issue by MiDo-kun** [LuanRT/YouTube.js#167]
node:internal/errors:464     
ErrorCaptureStackTrace(err);  

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({   message: 'Request failed with status code 400',   type: 'REQUEST_FAILED' })     at new NodeError (node:internal/errors:371:5)     at PassThrough.emit (node:events:379:17) at downloadChunk (C:\Users\smido\Desktop\Group Chat Bot\Youtube API\node_modules\youtubei.js\lib\Innertube.js:613:20) at processTicksAndRejections (node:internal/process/task_queues:96:5) {   code: 'ERR_UNHANDLED_ERROR', context: {message: 'Request failed with status code 400',     type: 'REQUEST_FAILED' }

**Comment by LuanRT** [comment]
Hey there, I see you're using v1.
If possible, please provide a code snippet so I can reproduce it and eventually fix it. Or you can just migrate to v2, see #65.

Thanks for reporting and have a great day!
