### ISSUE TITLE
2.0 getSubscriptionsFeed is always empty

### ISSUE THREAD

**Issue by yestoall** [LuanRT/YouTube.js#171]
### Question

any ideas or alternatives?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
It returns a `Feed` object, right? If so, then it isn't empty.
You can get its contents by using the getters available, ex:
```js
const subsfeed = await yt.getSubscriptionsFeed();

// Returns all shelves/segments from the page
console.log(subsfeed.shelves);

// Returns all videos 
console.log(subsfeed.videos);
```

**Comment by yestoall** [comment]
Great! thank you again for your great work
