### ISSUE TITLE
How can I get and add replies to comments?

### ISSUE THREAD

**Issue by edge-loop** [LuanRT/YouTube.js#18]
I've tried getting comments from videos, and using the continuation feature (all successfully), but I'm wondering if there's a way to get replies to the comments. Is this currently possible, and if so, how do I do it? I looked at the readme and didn't see anything about replies. Also, on a similar note, how can I post replies to specific comments, as opposed to just posting comments on just the video? Is this not a feature or is there a way to do that?

**Comment by LuanRT** [comment]
Hi! Getting comment replies or replying to a specific comment is not possible yet. However, I've been working on it and it'll probably be available in the next release.

**Comment by edge-loop** [comment]
Cool, thanks

**Comment by LuanRT** [comment]
Done, you may want to check the [updated documentation](https://github.com/LuanRT/YouTube.js/tree/V1.3.8#usage) if you still need this.
