### ISSUE TITLE
Bypass most of the age-restricted videos

### ISSUE THREAD

**Issue by unixfox** [LuanRT/YouTube.js#191]
### Describe your suggestion

Implement the client `TVHTML5_SIMPLY_EMBEDDED_PLAYER` for bypassing the age-restricted videos, cf: https://github.com/yt-dlp/yt-dlp/pull/3233

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Just released v2.2.1. Again, thanks!
