### ISSUE TITLE
v2.2.1 Video fetched through TVHTML5_SIMPLY_EMBEDDED_PLAYER give undefined URLs for streaming_data

### ISSUE THREAD

**Issue by unixfox** [LuanRT/YouTube.js#196]
### Steps to reproduce

1. Get the streaming data for the video `0hznKTGTmPg`.
2. undefined URLs are given for `adaptive_formats` nor `formats`.

Example code:
```javascript
import pkg from 'youtubei.js';
const { Innertube } = pkg;

const youtube = await Innertube.create();
const basicInfo = await youtube.getBasicInfo('0hznKTGTmPg', 'TV_EMBEDDED');
console.log(basicInfo.streaming_data);
```

### Failure Logs

```shell
Format {
      itag: 18,
      mime_type: 'video/mp4; codecs="avc1.42001E, mp4a.40.2"',
      bitrate: 359380,
      average_bitrate: undefined,
      width: 640,
      height: 360,
      init_range: undefined,
      index_range: undefined,
      last_modified: 2022-02-16T04:38:44.452Z,
      content_length: NaN,
      quality: 'medium',
      quality_label: '360p',
      fps: 30,
      url: undefined,
      cipher: undefined,
      signature_cipher: 's=AOq0QJ8wRQIgEhlFhkfgkA2eN2FiVPbzBzqCOtn6qEnRo1GKYp4XZKcCIQDs1R2aARk58TR6nq3TACgrGrrVXqjiyN7veUmPJF%3D8-A%3Dd%3Dd&sp=sig&url=https://rr5---sn-5hneknek.googlevideo.com/videoplayback%3Fexpire%3D1663519536%26ei%3D0PYmY8qYHIjU1gKQ2KfQBQ%26ip%3D20.105.254.1%26id%3Do-ADZO32o5iYN91FiB80vUBfjHs13D2kTwZ02ZQG26OqYo%26itag%3D18%26source%3Dyoutube%26requiressl%3Dyes%26mh%3D1N%26mm%3D31%252C26%26mn%3Dsn-5hneknek%252Csn-4g5ednkl%26ms%3Dau%252Conr%26mv%3Dm%26mvi%3D5%26pl%3D17%26gcr%3Dnl%26initcwndbps%3D635000%26vprv%3D1%26xtags%3Dheaudio%253Dtrue%26mime%3Dvideo%252Fmp4%26ns%3DF1OMKEZ4duyW4Q6QcKaHo5QI%26cnr%3D14%26ratebypass%3Dyes%26dur%3D8976.277%26lmt%3D1644986324452292%26mt%3D1663497663%26fvip%3D2%26fexp%3D24001373%252C24007246%26c%3DTVHTML5_SIMPLY_EMBEDDED_PLAYER%26rbqsm%3Dfr%26txp%3D5438434%26n%3D29eDZKyf8IQ8Z189%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Citag%252Csource%252Crequiressl%252Cgcr%252Cvprv%252Cxtags%252Cmime%252Cns%252Ccnr%252Cratebypass%252Cdur%252Clmt%26lsparams%3Dmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%252Cinitcwndbps%26lsig%3DAG3C_xAwRQIgFhR_0UQokF2FdqvwgthXqYMBTEtd-hq5hIpHXVu4f80CIQDJ-YHYfRwO4zR3Qlpch9l-4SbqU_mXtTF8mywlz91weQ%253D%253D',
      audio_quality: 'AUDIO_QUALITY_LOW',
      approx_duration_ms: 8976277,
      audio_sample_rate: 22050,
      audio_channels: 2,
      loudness_db: undefined,
      has_audio: true,
      has_video: true
    }
```

### Expected behavior

Download URLs given in streaming_data

### Current behavior

No Download URLs given in streaming_data, only undefined URLs.

### Version

Default

### Anything else?

I've patched https://github.com/LuanRT/YouTube.js/blob/main/src/utils/HTTPClient.ts in order to include the missing data that I explained in https://github.com/LuanRT/YouTube.js/pull/193#issuecomment-1250233418

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by itsmenewbie03** [comment]
checkout my pull request https://github.com/LuanRT/YouTube.js/pull/195#issue-1377014529 . I tested the Example code you included in I did not encounter any issues.

**Comment by unixfox** [comment]
> checkout my pull request [#195 (comment)](https://github.com/LuanRT/YouTube.js/pull/195#issue-1377014529) . I tested the Example code you included in I did not encounter any issues.
> 
> here is a copy of the response: [steaming_data.txt](https://github.com/LuanRT/YouTube.js/files/9593833/steaming_data.txt)

I'm still getting undefined URLs with your PR, I think the decryption code doesn't work for this new Client.

**Comment by itsmenewbie03** [comment]
> > checkout my pull request [#195 (comment)](https://github.com/LuanRT/YouTube.js/pull/195#issue-1377014529) . I tested the Example code you included in I did not encounter any issues.
> > here is a copy of the response: [steaming_data.txt](https://github.com/LuanRT/YouTube.js/files/9593833/steaming_data.txt)
> 
> I'm still getting undefined URLs with your PR, I think the decryption code doesn't work for this new Client.
> 
> ```
> Format {
>       itag: 22,
>       mime_type: 'video/mp4; codecs="avc1.64001F, mp4a.40.2"',
>       bitrate: 1582183,
>       average_bitrate: undefined,
>       width: 1280,
>       height: 720,
>       init_range: undefined,
>       index_range: undefined,
>       last_modified: 2022-01-30T20:09:14.990Z,
>       content_length: NaN,
>       quality: 'hd720',
>       quality_label: '720p',
>       fps: 30,
>       url: undefined,
>       cipher: undefined,
>       signature_cipher: 's=AOq0QJ8wRQIgUBrvjjvX8DChbUeYkI9DK4n1GRa_u-pP7mZUUO3J1GYCIQCPHR6Px926W0-jfpqt3KHzbc85BPRy-L4fVATBI2%3Djww%3DZ%3DZ&sp=sig&url=https://rr5---sn-5hneknek.googlevideo.com/videoplayback%3Fexpire%3D1663524479%26ei%3DHwonY4WWCMGmgQf8lSE%26ip%3D52.148.209.167%26id%3Do-AJ1UM55AJDpqypEjc3z3SCnaQTIu_unoyE3IEjNy6mL5%26itag%3D22%26source%3Dyoutube%26requiressl%3Dyes%26mh%3D1N%26mm%3D31%252C26%26mn%3Dsn-5hneknek%252Csn-4g5ednkl%26ms%3Dau%252Conr%26mv%3Dm%26mvi%3D5%26pl%3D18%26gcr%3Dnl%26initcwndbps%3D1252500%26vprv%3D1%26mime%3Dvideo%252Fmp4%26ns%3DdnAJGNC6AzA0R-oVsdt3fp0I%26cnr%3D14%26ratebypass%3Dyes%26dur%3D8976.230%26lmt%3D1643573354990133%26mt%3D1663502471%26fvip%3D2%26fexp%3D24001373%252C24007246%26c%3DTVHTML5_SIMPLY_EMBEDDED_PLAYER%26rbqsm%3Dfr%26txp%3D5432434%26n%3DBEmoHePFxcsy9zDh%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Citag%252Csource%252Crequiressl%252Cgcr%252Cvprv%252Cmime%252Cns%252Ccnr%252Cratebypass%252Cdur%252Clmt%26lsparams%3Dmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%252Cinitcwndbps%26lsig%3DAG3C_xAwRAIgBWNhxn3px4QhUlWP0M2u4z6IzBqQwN2WafE4KSvQEKoCIGoU-sLtQxgwB7wJNpinSo97L-bT09pZBdUN0X6N5CT6',
>       audio_quality: 'AUDIO_QUALITY_MEDIUM',
>       approx_duration_ms: 8976230,
>       audio_sample_rate: 44100,
>       audio_channels: 2,
>       loudness_db: undefined,
>       has_audio: true,
>       has_video: true
>     }
> ```

guess we've still got a lot of things to work. xD

**Comment by Wykerd** [comment]
@unixfox The `url` doesn't need to be defined, `signature_cipher` is used to compute the final url. You must use `Format#decipher` to get the final url.

**Comment by LuanRT** [comment]
@Wykerd is right.
You can simply call the decipher method every `Format` has, ex:
```js
const info = await yt.getBasicInfo('somevideoid');
const url = info.streaming_data.formats[0].decipher(yt.session.player);
```
