### ISSUE TITLE
Best way to get info-cards?

### ISSUE THREAD

**Issue by glesperance** [LuanRT/YouTube.js#199]
### Question

Hey everyone, 
very happy to have found this library ; it's been very helpful on a project I am working on.

Would anyone be able to tell me what is the easiest way to get info-cards data using the library? I have looked at `VideoInfo.cards` but it does not seem to have any content there.

Cheers!

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hey there, they should be in `VideoInfo.cards`. What does `info.cards?.cards` look like for you? Is it `null`?

If it isn't then I reckon you're getting a few `SuperParsedResult` objects here and there (`teaser` & `content`?) which may appear to be empty when in fact, they aren't. If that's the case then [this](https://github.com/LuanRT/YouTube.js/tree/main/src/parser#superparsedresponse) should help you for now.

**Comment by LuanRT** [comment]
I think you are still on v2.2.2, just tested and those props aren't empty for me. Update the library and let me know if it works.

**Comment by glesperance** [comment]
Yep that was it. I guess I updated my packages and 2.2.3 was released later the same day.
Thanks!
