### ISSUE TITLE
1.4.0 getSearchSuggestions throwing TypeError

### ISSUE THREAD

**Issue by levno-710** [LuanRT/YouTube.js#20]
## Expected Behavior
getSearchSuggestions should return search suggestions.

## Current Behavior
The following Error is thrown:
```
TypeError: Cannot set properties of undefined (setting 'context')
    at Object.music (node_modules\youtubei.js\lib\core\Actions.js:181:20)
    at Innertube.getSearchSuggestions (node_modules\youtubei.js\lib\Innertube.js:384:38)
```

## Fix
Change line 180-183 of ```lib\core\Actions.js``` from
```javascript
case 'get_search_suggestions': 
      data.context = context;
      data.input = args.input || '';
      break;
```
to
```javascript
case 'get_search_suggestions': 
      data = {};
      data.context = context;
      data.input = args.input || '';
      break;
```

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information

**Comment by LuanRT** [comment]
Hello,
Thanks for reporting! That slhould be fixed now.
