### ISSUE TITLE
Update Metadata of Existing Videos

### ISSUE THREAD

**Issue by gunpal5** [LuanRT/YouTube.js#208]
### Describe your suggestion

I see, there's no way to update the metadata of the existing videos. Is it possible to add that feature into Video.js?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
I'll probably start working on this after #202 is done. But feel free to do it if you feel like contributing. 
Thanks!

**Comment by LuanRT** [comment]
This should now be possible in v2.3.2. if you can please do test it and let me know if it's working correctly!
