### ISSUE TITLE
Manage scope

### ISSUE THREAD

**Issue by ofahi-qalqul** [LuanRT/YouTube.js#211]
### Question

how to add url scope for oauth , please i need 

### Other details

give me solution brother tnks

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Heya, is there a specific use case for this? I'm pretty sure YouTube's OAuth server rejects any other type of scope.
