### ISSUE TITLE
[2.3.2] InnertubeError: Request to URL failed with status 401

### ISSUE THREAD

**Issue by salman0ansari** [LuanRT/YouTube.js#221]
### Steps to reproduce

I am trying to upload a video 
as soon sign in completes 
401 error comes

### Failure Logs

```shell
Hello!
On your phone or computer, go to https://www.google.com/device and enter the code CVYG-SVLT
Successfully signed in!
/home/salman/Desktop/YOUTUBE/node_modules/youtubei.js/dist/src/utils/HTTPClient.js:112
            throw new Utils_1.InnertubeError(`Request to ${response.url} failed with status ${response.status}`, yield response.text());
                  ^

InnertubeError: Request to https://upload.youtube.com//upload/youtubei?prettyPrint=false&alt=json failed with status 401
    at HTTPClient.<anonymous> (/home/salman/Desktop/YOUTUBE/node_modules/youtubei.js/dist/src/utils/HTTPClient.js:112:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/salman/Desktop/YOUTUBE/node_modules/youtubei.js/dist/src/utils/HTTPClient.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  info: '{"status":"STATUS_REJECTED","rejectionReason":"REJECTED_NOT_AUTHENTICATED"}',
  date: 2022-10-14T18:10:00.933Z,
  version: '2.3.2'
}
```

### Expected behavior

upload video 

### Current behavior

crashing 

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
You are trying to upload from a brand account, right? If so, then it isn't possible, unfortunately only normal accounts are supported at the moment.

**Comment by salman0ansari** [comment]
> You are trying to upload from a brand account, right? If so, then it isn't possible, unfortunately only normal accounts are supported at the moment.

yes, I was using a brand account never mind I will use normal account.
thanks for the quick response

**Comment by flolep2607** [comment]
even for normal account i get the same error

**Comment by damian123** [comment]
> You are trying to upload from a brand account, right? If so, then it isn't possible, unfortunately only normal accounts are supported at the moment.

It is possible to add support for brand accounts?
