### ISSUE TITLE
2.3.2 Why are posted comments not visible sometimes?

### ISSUE THREAD

**Issue by slidenerd** [LuanRT/YouTube.js#224]
### Steps to reproduce

I honestly dont know how to reproduce this but there are some videos where you get a success response on YouTube. They have comments enabled and you can clearly see a few other people's comments but yours is the only comment that is not visible
Example video
[My hello message is not visible on this video at all](https://www.youtube.com/watch?v=oNtAbdFkx3M) or even on [this](https://www.youtube.com/watch?v=tjnhcbLg-Es) one

### Failure Logs

```shell
No logs
```

### Expected behavior

The comment should be visible on every video when success is true

### Current behavior

The comments are not visible sometimes

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by slidenerd** [comment]
**UPDATE 1**

 I pasted the same code and ran it from repl.it and it is posting the comments. Does this have to do something with the access/refresh token? Is it possible that it is not getting refreshed properly?

**Comment by LuanRT** [comment]
I don't think it has anything to do with the access token, but rather YouTube's anti spam thingy kicking in. This also happens on official clients, it basically deletes your comment or just shadowbans it.

Having said that, it doesn't seem like we can do anything about it.

**Comment by slidenerd** [comment]
i ll close the issue but one last question, do you have idea why its gets triggered. i am generating responses randomly from one of the 1000 predefined responses and posting only once every 10 mins or so, i have no idea how this anti spam system kicks in

**Comment by LuanRT** [comment]
> i ll close the issue but one last question, do you have idea why its gets triggered. i am generating responses randomly from one of the 1000 predefined responses and posting only once every 10 mins or so, i have no idea how this anti spam system kicks in

If possible, could you check the response data of those that aren't posted? Maybe there's something in there that could hint us on what's causing it. But again, it's most likely just normal behavior from YouTube.
