### ISSUE TITLE
v1.4.5 `Innertube.getDetails` results in an exception

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#225]
### Steps to reproduce

Hi. Lately, YouTube has been rolling out some sort of a redesign to their app and website, seemingly breaking older versions of `YouTube.js`. I haven't tested it on the newest version yet. I hope the v1 branch is still somewhat supported because I might not have the time to migrate my project to v2.

As for reproducing the issue, just try calling `Innertube.getDetails` on any video in v1.4.5.

### Failure Logs

```
/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/index.js:235
        .topLevelButtons.find((item) => item.toggleButtonRenderer.defaultIcon.iconType == 'LIKE');
                                                                  ^

TypeError: Cannot read properties of undefined (reading 'defaultIcon')
    at /home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/index.js:235:67
    at Array.find (<anonymous>)
    at Parser.#processVideoInfo (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/index.js:235:26)
    at Object.VIDEO_INFO (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/index.js:34:51)
    at Parser.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/index.js:37:22)
    at Innertube.getDetails (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/Innertube.js:201:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (file:///home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/index.js:231:32)

Node.js v17.9.0
```

### Version
Default

### Checklist
- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by sabuone** [comment]
/node_modules/youtubei.js/lib/parser/index.js

/*
      const like_btn = primary_info_renderer.videoActions.menuRenderer
        .topLevelButtons.find((item) => item.toggleButtonRenderer.defaultIcon.iconType == 'LIKE');

      const dislike_btn = primary_info_renderer.videoActions.menuRenderer
        .topLevelButtons.find((item) => item.toggleButtonRenderer.defaultIcon.iconType == 'DISLIKE');
*/
      const like_btn = true;
      const dislike_btn = true;

**Comment by LuanRT** [comment]
Sure, I'll see what I can do about that. And sorry for the delay, I've been quite busy lately.

**Comment by walking-octopus** [comment]
Hi. Is there anything that could be done to fix this? Should I start migrating to v2?

**Comment by LuanRT** [comment]
> Hi. Is there anything that could be done to fix this? Should I start migrating to v2?

Heya @walking-octopus, you could try patching the code inside your node_modules manually as suggested by @sabuone. I plan to update v1 (on npm) but I do recommend you to migrate to v2. You see, more and more stuff will begin to break in v1, as its parser is quite inefficient.
