### ISSUE TITLE
Get basic info from yt music.getArtist() call.

### ISSUE THREAD

**Issue by titong0** [LuanRT/YouTube.js#226]
### Question

Is there any way to get a channel's Name and profile picture? my old code looked like this
```javascript
  const artist = await client.music.getArtist(channelId);

  return {
      name: artist.header?.title.text,
      avatar: artist.header.thumbnail?.contents,
      description: artist.header.description.text,
      id: channelId,
    }
```
but as of version 2.3.0, `artist.header.title` is possibly undefined. 
`thumbnail` and `description` are only present in `MusicVisualHeader` and `MusicInmersiveHeader`. but `artist.header` can also be `MusicHeader` which doesn't have them. 

1. How can I get the channels name without having to do optional chaining? (I feel like `artis.header?.title.text` could break)
2. How can I get the avatar and (if present) description?

### Other details

I saw [this issue](https://github.com/LuanRT/YouTube.js/issues/207) but I'm pretty sure this information could be obtained without an additional call.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by itsmenewbie03** [comment]
Not sure if this is the best approach but this could work xD
```js
    const artist = await yt.music.getArtist(cId);
    const name = artist.header.title?.text;
    if (artist.header.type === 'MusicVisualHeader') {
        //has profile pic probably
        var avatar = artist.header.foreground_thumbnails[0].url
    }
    else if (artist.header.type === 'MusicImmersiveHeader') {
        //has banner
        var desc = artist.header.description?.text
        var avatar = artist.header.thumbnail.contents[0].url
    }
```

**Comment by LuanRT** [comment]
`MusicHeader` is used in other pages where it doesn't need a title, but I doubt that will ever be the case for artist pages, so I wouldn't worry about that. And as for the description, profile pictures and banners you'll have to manually check the header type. If it helps, YouTube Music seems to favor `MusicImmersiveHeader`.

**Comment by titong0** [comment]
Thanks! I'll try this method out.
