### ISSUE TITLE
v2.2.2 Can't chose what account to use in the browser when user has multiple

### ISSUE THREAD

**Issue by terrygonguet** [LuanRT/YouTube.js#229]
### Steps to reproduce

This issue impacts 2 web extensions I've made to improve YT, the easiest way to reproduce is to install the [Subscribe to Youtube Playlists](https://youtube-extensions.gonguet.com/sub-to-playlists).

1. Install extension
2. Create second YT account (I'm not sure if they have to both use the same email, behaviour seems weird) and link them
3. Swap accounts
4. The extension only returns data from the first account, not the one currently logged in

### Failure Logs

```shell
This is a silent error.
```

### Expected behavior

I would expect the InnerTube instance to fetch data from the account currently logged in (or at least the one currently selected).

### Current behavior

The data returned is from the same account, no matter what account the user switches to.

### Version

Default

### Anything else?

The InnerTube instance is created like this on page load:

```js
const youtube = await Innertube.create({
	cookie: document.cookie,
	fetch: (...args) => fetch(...args),
})
```

In [this file](https://github.com/terrygonguet/sub-to-yt-playlist/blob/master/ui/src/lib/data.js).

### Checklist

- [ ] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Ok, so I figured this out and it's simpler than I thought.
To choose an account we have to pass the header `x-goog-authuser` with the index of the account.

For example, say you have 3 accounts on a cookie — to choose the second one `x-goog-authuser` would have to be set to 2.

I'll probably make this into a parameter in the `Innertube#create` method.
