### ISSUE TITLE
Can this be used in the browser?

### ISSUE THREAD

**Issue by johtso** [LuanRT/YouTube.js#23]
I'd like to write a client side app that presents videos scraped from youtube, is it possible to use this library in the browser?

**Comment by LuanRT** [comment]
I don't think so, never tried but you'll probably face CORS problems & other issues related to how the library caches the yt player.

**Comment by Deagle50** [comment]
Hi! I wanted to do something similar, so I forked the project and made it api-rest like. Right now only search is working, as it's the only method I needed, but any method can be implemented at will. Thanks LuanRT for your good work!
