### ISSUE TITLE
Is it still possible to get YTMUSIC suggestions

### ISSUE THREAD

**Issue by GlxryX** [LuanRT/YouTube.js#238]
### Question

Previously, you could use the following to specifically search YouTube music for suggestions and get only songs specifically.
```javascript
const suggestions = await youtube.getSearchSuggestions('QUERY', {
   client: 'YTMUSIC'
})
```
now, the function is nowhere to be found in the docs

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by GlxryX** [comment]
additionally, is the function also gone for the `.search()` method as well?

**Comment by LuanRT** [comment]
YouTube Music docs can be found [here](https://github.com/LuanRT/YouTube.js/blob/main/docs/API/music.md), I did not remove any feature from previous version. I should say though, as of last week YouTube Music no longer allows unauthenticated users to retrieve search suggestions, so if you want that you'll have to log in.

**Comment by GlxryX** [comment]
> as of last week YouTube Music no longer allows unauthenticated users to retrieve search suggestions

How would I provide an authentication token to allow for the retrieval of search suggestions, is it through Innertube?

**Comment by LuanRT** [comment]
See the [examples folder](https://github.com/LuanRT/YouTube.js/tree/main/examples/auth). You can also log in with cookies.
