### ISSUE TITLE
Usage with nextjs

### ISSUE THREAD

**Issue by d1ndonlymdhe** [LuanRT/YouTube.js#241]
### Question

How to use this library with nextjs api routes and getserversideprops?

### Other details

I was trying to use the search function but get the following error while using with nextjs
![image](https://user-images.githubusercontent.com/84237807/202689188-fdd3e116-6aa9-422d-a384-3200bd42daef.png)
![image](https://user-images.githubusercontent.com/84237807/202689320-3697b368-cc4a-463e-9a9a-d391c37276b3.png)

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by titong0** [comment]
Could you show your code? I'm using it with next.js too and it is working fine

**Comment by d1ndonlymdhe** [comment]
I don't have the original code but I used it like this.
[stackblitz demo](https://stackblitz.com/edit/nextjs-d2jqea?file=pages/api/hello.js)
