### ISSUE TITLE
account.getinfo method changed?

### ISSUE THREAD

**Issue by canyesilyurt** [LuanRT/YouTube.js#252]
### Question

Hello, has the getinfo method changed? User information, e-mail address etc.

youtube.account.getInfo()).name log undefined

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hey,
Yes, you're right. It's still there though, the only thing that changed is how the data is structured.

**Comment by canyesilyurt** [comment]
I just used youtube.account.getInfo(YTNodes.ChannelAboutFullMetadata) method and got the same result again :D

**Comment by canyesilyurt** [comment]
Version 1.4.4 getinfo function

![image](https://user-images.githubusercontent.com/36952967/206653659-46027c84-e373-4738-b398-196487007686.png)

Last version getinfo

![image](https://user-images.githubusercontent.com/36952967/206653746-bcaa021d-5eeb-47e4-a99d-b1698c05a19c.png)

**Comment by LuanRT** [comment]
> I just used youtube.account.getInfo(YTNodes.ChannelAboutFullMetadata) method and got the same result again

That's not how you're supposed to access it. All the info you need should be available in the `contents` object.
```ts
const info = await yt.account.getInfo();
console.log(info.contents)
```

**Comment by canyesilyurt** [comment]
> > I just used youtube.account.getInfo(YTNodes.ChannelAboutFullMetadata) method and got the same result again
> 
> That's not how you're supposed to access it. All the info you need should be available in the `contents` object.
> 
> ```ts
> const info = await yt.account.getInfo();
> console.log(info.contents);
> ```

Yes, I looked a little. Then I was able to pull the account name, mail, avatar and follower count, but I couldn't find the channel id.

**Comment by canyesilyurt** [comment]
eExcellent
