### ISSUE TITLE
How to use 'setNotificationPreferences'?

### ISSUE THREAD

**Issue by canyesilyurt** [LuanRT/YouTube.js#257]
### Question

Hi, I am using the setNotificationPreferences action success returns true but not updating. Why is this happening?

Data: Channel id & type

![image](https://user-images.githubusercontent.com/36952967/208220547-31a4a12c-28d2-439f-af92-b21d9d15f7f6.png)

![image](https://user-images.githubusercontent.com/36952967/208220584-c7fe25f9-5de6-438f-925e-e504eaf4a082.png)

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hey @canyesilyurt, seems like you found a bug.

The wrong client is being used to make the request here:
https://github.com/LuanRT/YouTube.js/blob/b036e2fcdc0d7fdad4802aa6b9072fbeb50350bb/src/core/InteractionManager.ts#L178

It should he `WEB` and not `ANDROID`. You can submit a pull request if you're willing to fix it yourself or wait until the next release (probably tomorrow or next week).

Thanks for reporting!

**Comment by canyesilyurt** [comment]
> Hey @canyesilyurt, seems like you found a bug.
> 
> The wrong client is being used to make the request here:
> 
> https://github.com/LuanRT/YouTube.js/blob/b036e2fcdc0d7fdad4802aa6b9072fbeb50350bb/src/core/InteractionManager.ts#L178
> 
> It should he `WEB` and not `ANDROID`. You can submit a pull request if you're willing to fix it yourself or wait until the next release (probably tomorrow or next week).
> 
> Thanks for reporting!

You'r awesome <3
