### ISSUE TITLE
Allow specifying the location

### ISSUE THREAD

**Issue by absidue** [LuanRT/YouTube.js#259]
### Describe your suggestion

The YouTube website allows you to specify the location, this allows you to get content from other regions than your current one. Things like trending is different in each region, so being able to specify a different region allows you to see different content.

### Other details

The location is stored in the `gl` parameter, currently the library reads the value returned by YouTube in `Session#getSessionData`. However it should be possible just to override that value, like on the YouTube website.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
closing as this was implemented in #260

**Comment by absidue** [comment]
@LuanRT why did you make the location override the `accept-language` header?

If you specify `en-US` as the language and `DK` as the location, the accept language header is set to `en-US-DK`

**Comment by LuanRT** [comment]
I assumed YouTube would strip the geolocation out of the ISO code, and it does for most lang codes except for that one and a few others. I think the solution here will be setting `Accept-Language` to `*`. 

You see, as long as `hl` & `gl` are present in the `context` object YouTube will ignore this header.

**Comment by absidue** [comment]
I'm sure it strips it out for some languages, however YouTube en-US and en-GB are actually different (words, gammer and capitalisation), so YouTube has separate language options for them. If the language is set to one of the three English options that YouTube has `hl` will have these values:
English (US) -> `en`
English (UK) ->`en-GB`
English (India) -> `en-IN`

![langs](https://user-images.githubusercontent.com/48293849/208522386-c6fbceae-8b5f-448c-af61-3841dcbd08d8.png)

Out of curiosity, if YouTube ignores the header anyway, why do you specify it in the request?

**Comment by LuanRT** [comment]
> I'm sure it strips it out for some languages, however YouTube en-US and en-GB are actually different (words, gammer and capitalisation), so YouTube has separate language options for them. If the language is set to one of the three English options that YouTube has `hl` will have these values: English (US) -> `en` English (UK) ->`en-GB` English (India) -> `en-IN`

I see, thanks.

> Out of curiosity, if YouTube ignores the header anyway, why do you specify it in the request?

Probably just to stay on par with YouTube. 
And as far as I can tell, it is always set to `en-US` on the website, regardless of the language you choose. So I'll just change it to `*`.

**Comment by absidue** [comment]
Ah on the website it's probably set by your web browser, so it'll be whatever languages you have configured in your web browser. If it gets ignored anyway for all of the requests, setting it to `*` is probably the best, as you said.

**Comment by absidue** [comment]
Closing this again as the changes have been made to the main branch
