### ISSUE TITLE
Can't I use MP3 format or 360p UP?

### ISSUE THREAD

**Issue by sabuone** [LuanRT/YouTube.js#27]
Hi.

I'm using your library well.

I think I can replace YouTube-dl, so I think mp3 format or 360p quality doesn't work during the function test.

Are you willing to update it?

**Comment by LuanRT** [comment]
That is because YouTube doesn't provide mp3 formats + YouTube-dl uses ffmpeg to convert the file. If you exclusively need that format for some reason then you should use something like fluent-ffmpeg to convert it:

```js
//....
ffmpeg(stream)
  .audioBitrate(128)
  .save('./test.mp3')
  .on('end', () => console.info('Done!'));
```
