### ISSUE TITLE
Is there a way to increase the number of search results?

### ISSUE THREAD

**Issue by levno-710** [LuanRT/YouTube.js#28]
I am using the following code to fetch music search results for a given query
```javascript
const songs = await youtube.search(query, { client: 'YTMUSIC' }).result.songs;
```

This always gives me 3 songs.
Is there a way to get more results?

**Comment by LuanRT** [comment]
Hello,
That's just how YouTube Music search works by design, there's a way to get more results but I haven't implemented it in the library yet.
