### ISSUE TITLE
YouTube kids support

### ISSUE THREAD

**Issue by ChunkyProgrammer** [LuanRT/YouTube.js#284]
### Describe your suggestion

Add support for YouTube kids.
YouTube kids uses InnerTube and since YouTube music is already supported I figured it wouldnt hurt to open a request.
This would be useful for searching for Kid Friendly Content as well as getting dedicated feeds for the content.

### Other details

YouTube Kids (workflow to get to content): https://www.youtubekids.com/
- Click `I'm a Parent`
- Click `Next`
- Enter 1989 (or any year, really. Maybe use current year - 30?)
- Unskippable 25 second video plays
- Click Next
- Click Skip (Or sign in)
- Click "I agree"
- Set child age ( < 4, 5-8 or 9-12)
- Enable/Disable search
- See home page

Note: 
Some URLS can be written as YouTube urls.
Ex:
https://www.youtubekids.com/watch?v=LRKB6WzT9kc => https://www.youtube.com/watch?v=LRKB6WzT9kc
https://www.youtubekids.com/channel/UCMryAHWeLf3TxDyDxSWs4AQ => https://www.youtube.com/channel/UCMryAHWeLf3TxDyDxSWs4AQ

The video + channel pages do hold different data when viewing with YouTube Kids
![image](https://user-images.githubusercontent.com/78101139/211451414-e66825a6-e333-4a85-ad77-e8f09b020d3b.png)

![image](https://user-images.githubusercontent.com/78101139/211451651-86397610-c14f-40db-bca5-e7070ed66aac.png)

Some videos dont have subscribe button and dont link back to the channel:
![image](https://user-images.githubusercontent.com/78101139/211451765-29d333dc-db4f-4001-8325-7e5385685364.png)

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
I considered implementing this a while ago but ended up forgetting. Do you know if the InnerTube requests made by this client require authentication? I've played around with the `/player` and `/next` endpoints and both seemed to work without OAuth/Cookies, but I'm mostly curious about the recommendation feeds as well as search.

**Comment by ChunkyProgrammer** [comment]
I havent used InnerTube for it but using the website, I was able to use YT Kids without OAuth (cookies were needed for this but the cookies might not be needed for InnerTube). I'll see if I can find any more info

**Comment by LuanRT** [comment]
Alright, thanks!

I did some more testing and it seems that almost all endpoints work without Cookies/OAuth. I'll be working on this feature [here](https://github.com/LuanRT/YouTube.js/tree/feat/ytkids-support).
