### ISSUE TITLE
Add support for the channel termination reasons

### ISSUE THREAD

**Issue by absidue** [LuanRT/YouTube.js#289]
### Describe your suggestion

For channels that have been deleted or terminated for violating rules, YouTube provides an alert message with a reason instead of just returning a 404 page. Currently YouTube.js throws an [`Invalid channel` error](https://github.com/LuanRT/YouTube.js/blob/main/src/parser/youtube/Channel.ts#L36), in the cases where YouTube provides a reason it would be nice to get that reason instead of generic error message.

How you want to implement it, is of course entirely up to you, however it would be nice to be able to identify between the generic error and the YouTube alert. One thought I had would be to use a different error class, that way a user of the library could use `instanceof` in their catch block to work out what type it is.
The reason for the separation is that we would like to show the reason to the user in FreeTube, if there is one and fall back to Invidious for any non alert errors.

Here are some example channels:
https://www.youtube.com/channel/UCDzb8yXGOm6ZYd0Jf_FYKWA
https://www.youtube.com/channel/UC59AcfHD5jOGqTxb-zAsahw
(Taken from https://github.com/FreeTubeApp/FreeTube/pull/2283)

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
See 0b991800a5c67f0e702251982b52eb8531f36f19. Channels that return an alert of type `ERROR` (those being terminated and nonexistent channels) should now throw a `ChannelError` instead of a generic InnerTube error.

**Comment by absidue** [comment]
Thank you :)
As always we really appreciate your work and that you actively maintain the library.
