### ISSUE TITLE
Could not retrieve watch page info: Invalid value "undefined" for header "x-goog-visitor-id"

### ISSUE THREAD

**Issue by UnbreakCode** [LuanRT/YouTube.js#3]
Downloading from YouTube is not possible due to this error.

"Could not retrieve watch page info: Invalid value "undefined" for header "x-goog-visitor-id" "

**Comment by LuanRT** [comment]
Yea, I've noticed this too but it would usually happen randomly. It seems like sometimes YouTube doesn't provide the visitorData and some other fields in the Innertube configuration json. And that ends up causing a lot of problems— I will try to find a more efficient way to fetch that data.

**Comment by LuanRT** [comment]
Closing this for now as it is no longer a problem when it comes to downloading, however I should probably investigate it more since YouTube might complain about it not being provided.
