### ISSUE TITLE
Feature: Get recomendation homepage

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#30]
Many custom YouTube clients were harmed by them removing the ability to get the homepage feed through the official API. I saw a couple mentions of the home page in InnerTube source code, so maybe someone should take a look at it and figure out what's possible.

**Comment by LuanRT** [comment]
That's already a feature, you can get recommendations using [`getHomeFeed()`](https://github.com/LuanRT/YouTube.js#get-home-feed). Some things are still missing (topics, community posts etc), but they'll be implemented soon.

Thanks!
