### ISSUE TITLE
Video+Audio downloads fail with error code 400

### ISSUE THREAD

**Issue by Andrews54757** [LuanRT/YouTube.js#304]
### Steps to reproduce

Test video ID: `H7i9Anh0_Dg`

```js
const stream = await this.videoInfo.download({
  type: "audio+video",
  quality: "best",
  format: "mp4"
});
```

### Failure Logs

<img width="1262" alt="fail" src="https://user-images.githubusercontent.com/13282284/216399311-a04f5021-54e7-4538-99df-0633920df4df.png">

### Expected behavior

The video downloads completely or rejects the promise with error code.

### Current behavior

Trying to download videos with Youtube.js fails because a download request is rejected with a `400` error code. Most of the requests are successful, but one is not. Rate limiting requests client-side has no effect, it appears that the same exact request fails every time. Different youtube videos also fail to download with similar behavior.

When the download fails, the promise is not rejected. Instead, it hangs forever causing the application to be stuck in an waiting state.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hi!
This is likely due to the range being invalid, are you using the `range` option? As you can see [here](https://github.com/LuanRT/YouTube.js/blob/b2900f48a7aa4c22635e1819ba9f636e81964f2c/src/utils/FormatUtils.ts#L85) these audio+video formats are usually downloaded in one request unless you force the range (which is really only required for the adaptive formats).

**Comment by Andrews54757** [comment]
Thank you for your help. I needed to use `video+audio` instead of `audio+video` since it checks for that string specifically. Note that the [example download code](https://github.com/LuanRT/YouTube.js/blob/main/examples/download/index.ts) also has the reversed order:

```js
   const stream = await yt.download(song.id as string, {
      type: 'audio', // audio, video or audio+video
      quality: 'best', // best, bestefficiency, 144p, 240p, 480p, 720p and so on.
      format: 'mp4' // media container format 
    });
```
