### ISSUE TITLE
Can i run it without Deno?

### ISSUE THREAD

**Issue by MarianCN** [LuanRT/YouTube.js#316]
### Question

I'm trying to deploy the project on my hosting, but the problem is that it can only run node.js, not Deno.

I have one page that searches youtube videos, like this https://github.com/LuanRT/YouTube.js#browser-usage
The Url is like mysite.com

And I have one proxy subdomain that does exactly this: https://github.com/LuanRT/YouTube.js/blob/main/examples/browser/proxy/deno.ts
The Url is like proxy.mysite.com

The problem is I can't actually run Deno on my proxy subdomain. 
Can you help me deploying it, or is it even possible?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hi!
The cors proxy can be written in any language & run on any platform really, it doesn't matter for the library. So having said that, you can simply rewrite it to run on node.
