### ISSUE TITLE
[1.4] [Sometimes no videos returned]

### ISSUE THREAD

**Issue by BigBalli** [LuanRT/YouTube.js#32]
## Expected Behavior

Always return videos details when estimated_results shows thousands of results

## Current Behavior

Videos array in search response is empty... but only sometimes. Run again a few seconds later and you have videos. Seems random. Perhaps rate limiting on the backend?

## Failure Information (for bugs)
{
  query: 'Monte Carlo 2022 Highlights Day',
  corrected_query: 'N/A',
  estimated_results: 426438,
  videos: [],
  getContinuation: [AsyncFunction (anonymous)]
}

## Checklist

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I have provided sufficient information

**Comment by LuanRT** [comment]
Thanks for your report, I am aware of that and it'll be fixed soon.

**Comment by gregkop** [comment]
I've also encountered this issue, I'd be happy to lend a hand and help work through this problem if you know whats causing it @LuanRT

**Comment by LuanRT** [comment]
> I've also encountered this issue, I'd be happy to lend a hand and help work through this problem if you know whats causing it @LuanRT

Thank you but don't worry, this has already been fixed in #44.
