### ISSUE TITLE
Type all YTNodes' `data` arg as `RawNode`

### ISSUE THREAD

**Issue by LuanRT** [LuanRT/YouTube.js#323]
Currently, most of the InnerTube nodes have their `data` arg typed as `any`. This isn't ideal and can cause some confusion. It should instead be typed as `RawNode` like it's done [here](https://github.com/LuanRT/YouTube.js/blob/a0e6cef00fb9e3f52593cec22704f7ddc1f7553e/src/parser/classes/ChannelAgeGate.ts#L19).

**Comment by chinmay021** [comment]
Hi @LuanRT , I am new to open source contribution. I would like to work on this.

**Comment by LuanRT** [comment]
@chinmay021 
Hello and welcome!

See the [guidelines](https://github.com/LuanRT/YouTube.js/blob/main/CONTRIBUTING.md) so you can properly set up your development environment. Also, you can find the `YTNode` classes [here](https://github.com/LuanRT/YouTube.js/tree/main/src/parser/classes). 

There are many files in that folder and it can be quite intimidating at first, but you do not have to edit all of them. Only do an amount you're comfortable with and then submit a PR.

**Comment by LuanRT** [comment]
> Should this issue be closed? Looks like the PR has been merged

Nope, there are still many files left to be updated.
