### ISSUE TITLE
Support Shared posts within comunity tab

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [LuanRT/YouTube.js#331]
### Describe your suggestion

While testing https://github.com/FreeTubeApp/FreeTube/pull/1568, i noticed that shared posts in the community tab aren't supported.

Here the creator shared an post on her timeline but it isn't showing on ours

https://user-images.githubusercontent.com/73130443/222265814-edc75d65-6ca1-48c8-bcca-79d8404167a7.mp4

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Wykerd** [comment]
![image](https://user-images.githubusercontent.com/45672955/222341279-639a93fa-fad0-48e3-a3f8-3dd36d6d6d7b.png)

Seems like we haven't implemented the SharedPost renderer yet.
