### ISSUE TITLE
oAuth example with expressJS

### ISSUE THREAD

**Issue by KartoffelToby** [LuanRT/YouTube.js#35]
## Question
Looking through your code, i haven't an idea to handle a youtube login via oauth over a expressJS route

**Comment by LuanRT** [comment]
Hello,
Not sure if I can help you with that as I have no experience with ExpressJs but other than that it shouldn't be too difficult. Maybe someone else can assist you.

**Comment by LuanRT** [comment]
> what is there inside this file? yt_oauth_creds.json I wish the example at least included which keys are there with some dummy values inside

Hello @slidenerd , sorry for that.
It contains the OAuth credentials, it goes as follows:
```js
{
  access_token: string,
  refresh_token: string, 
  expires: Date
}
````

* Access token -
A bearer token is used to sign in to the account. It usually expires in 24 hours.

* Refresh token -
It is valid until you manually revoke access through your account or call the `signOut()` method. It is used to refresh the access token once it expires.

* Expires -
It is the expiry date of the access token.
