### ISSUE TITLE
Any type of connection fails when using with next.js.

### ISSUE THREAD

**Issue by titong0** [LuanRT/YouTube.js#350]
After updating to V3.3.0, I'm getting multiple crashes for any code that uses the library, even 
```javascript
const youtube = Innertube.create();
```
The error I'm getting looks like this:
```
error - unhandledRejection: TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at Y (C:...\node_modules\next\dist\compiled\@edge-runtime\primitives\streams.js:234:11)
    at C:\..\node_modules\next\dist\compiled\@edge-runtime\primitives\streams.js:1775:50
    at ReadableStream.pipeThrough (C:...\node_modules\next\dist\compiled\@edge-runtime\primitives\streams.js:1778:6)
    at fetchFinale (C:...\node_modules\undici\lib\fetch\index.js:973:52)
    at mainFetch (C:...\node_modules\undici\lib\fetch\index.js:773:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
I don't know wether this is a next.js thing but it wasn't happening before updating to 3.3.0. 

_Originally posted by @titong0 in https://github.com/LuanRT/YouTube.js/issues/279#issuecomment-1464940746_

**Comment by LuanRT** [comment]
I'm not familiar with Next.js so I can't tell. I've done a few tests and the latest version does work with other web frameworks such as Vue or even pure JavaScript + HTML though, so it is probably unrelated to the library. 

And speaking of which, what do your imports look like?

See (taken from the [documentation](https://github.com/LuanRT/YouTube.js#browser-usage)):
  ```ts
// Unbundled ESM version
import { Innertube } from 'youtubei.js/web';
```
```ts
// Bundled ESM version
import { Innertube } from 'youtubei.js/web.bundle';
```
```ts
// Production Bundled ESM version
import { Innertube } from 'youtubei.js/web.bundle.min';
```

**Comment by titong0** [comment]
I've been importing it like this since I first started using the library.
```javascript
import { Innertube } from "youtubei.js";
```
I'm realizing this may not be the way though. Is there any documentation about the different imports?

**Comment by titong0** [comment]
I'm importing like this 
```javascript
import { Innertube } from "youtubei.js";
```
Is there any documentation about the different imports? When should I use one or the other?

**Comment by absidue** [comment]
@titong0 if next.js is anything like webpack, it's picking the node.js import instead of the web one, despite the output target being a web browser, so you can use one of the 3 above to force it to use a web one.

**Comment by titong0** [comment]
The problem is, nextjs runs on both server and client. In my case its only running on the server so I think a node.js version would actually be ideal?

**Comment by titong0** [comment]
In case this happened to anyone. Running `npm update` seemed to solve things. Don't know what happened though. Thanks for the help!
