### ISSUE TITLE
Add support for editing channel name

### ISSUE THREAD

**Issue by LuanRT** [LuanRT/YouTube.js#40]
## Expected Behavior

The mobile version of YouTube allows one to edit the name of their channel without going to YouTube Studio, the library should be able to do that as well.

## Current Behavior

Not supported.

## Sample Code

That can be done by sending a post request to the `/channel/edit_name` endpoint with a protobuf payload that consists of [`context`](https://github.com/LuanRT/YouTube.js/blob/6bdccb89e5bece8daa19961fa415835824ae8aca/lib/proto/youtube.proto#L5) and the new name.

**Comment by barefootford** [comment]
Have you looked into making this work at all with the Youtube Studio APIs?
Right now I'm trying to parse and extract some of their internal json (https://studio.youtube.com/youtubei/v1/analytics_data/join?) to use for A/B testing thumbnails.

Great work so far 👍

**Comment by LuanRT** [comment]
> Have you looked into making this work at all with the Youtube Studio APIs? 

Yup, there's been a few suggestions regarding that [here](https://github.com/LuanRT/YouTube.js/discussions/24).
