### ISSUE TITLE
Release Tab for Youtube Artist channel

### ISSUE THREAD

**Issue by RikiNozomu** [LuanRT/YouTube.js#410]
### Describe your suggestion

Please add a new feature for list playlist from release tab.
<img width="1316" alt="Screenshot 2566-05-23 at 15 04 12" src="https://github.com/LuanRT/YouTube.js/assets/112609403/706d96c0-50a4-4f71-a6d0-93f8875a8e6a">

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Wow, I didn't know about this tab. Cool!

You can actually fetch any tab you want even if the library doesn't support it officially.

```ts
import { Innertube, YT } from 'youtubei.js';

(async () => {
  const yt = await Innertube.create();
  
  const channel = await yt.getChannel('UC5CwaMl1eIgY8h02uZw7u8A');
 
  if (channel.hasTabWithURL('releases')) {
    const tab = await channel.getTabByURL('releases');
    const releasesTab = new YT.Channel(yt.actions, tab.page, true);
    console.log(releasesTab);
    console.log(releasesTab.playlists);
  }
})();
```

I hope this helps!
