### ISSUE TITLE
a11e596 Terminated

### ISSUE THREAD

**Issue by RfadnjdExt** [LuanRT/YouTube.js#412]
### Steps to reproduce

1. Use [upload example file](https://github.com/LuanRT/YouTube.js/blob/main/examples/upload/index.ts).
2. Run it.

### Failure Logs

```shell
Terminated
```

### Expected behavior

A succesful upload.

### Current behavior

Terminated
No error, no warning.

### Version

Edge

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hi! Can you clarify a bit? By terminated do you mean the upload simply stops with no warning?

**Comment by RfadnjdExt** [comment]
Affirmative, it only write Terminated output.

**Comment by RfadnjdExt** [comment]
I think the issue is resolved somehow in the current version.

**Comment by RfadnjdExt** [comment]
I am reopening this issue to provide updated information regarding the previous "Terminated" problem encountered. Additionally, I want to share new details about the available RAM during the testing process.

1. Use the example file with a size of 1.1 GiB.
2. Execute the upload process.
3. Observe the outcome.

The upload process terminates and only outputs "Terminated". No error messages or other warnings are displayed.

Successful upload should occur.

The upload process halts with the "Terminated" output. No error messages or warnings are shown.

The version used is Edge.

During the testing, the system had 984 MiB of RAM available.

No response was provided.

- 1.1 GiB file that resulted in the "Terminated" message.
- 221 MiB file that was successfully uploaded.

Thank you for your attention to this matter. I hope this information, along with the RAM details, can help in resolving the "Terminated" issue I experienced previously. If there are further steps I need to take, please let me know.

**Comment by RfadnjdExt** [comment]
In this update, I will also propose a workaround that involves modifying the `#uploadVideo` method in the `fetch_function` function call.

**Workaround Proposal:**
You can try using the `createReadStream` function instead of `readFileSync` and add a new property called `duplex` with the value set to `'half'` in the `#uploadVideo` method's `fetch_function` function call. Here's an example:

```javascript
const file = createReadStream('videoFile.mp4');

yt.studio.upload(file, {
    title: 'videoFile.mp4',
    description: new Date().toString(),
    privacy: 'UNLISTED'
})
```

And in the `#uploadVideo` method:

```javascript
async #uploadVideo(upload_url: string, file: BodyInit): Promise<UploadResult> {
    const response = await this.#session.http.fetch_function(upload_url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'x-goog-upload-command': 'upload, finalize',
            'x-goog-upload-file-name': `file-${Date.now()}`,
            'x-goog-upload-offset': '0'
        },
        body: file,
        duplex: 'half'
    });

    if (!response.ok)
        throw new InnertubeError('Could not upload video');

    const data = await response.json();

    return data;
}
```

Please note that while this workaround may help, it's not guaranteed to solve the issue, and there is a possibility that it could have unintended consequences.
