### ISSUE TITLE
Retrieve channel from handle @

### ISSUE THREAD

**Issue by chen-rn** [LuanRT/YouTube.js#413]
### Describe your suggestion

It's not as easy nowadays for an end user to find their channel id, is it possible to get the channel from the @handle?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by ChunkyProgrammer** [comment]
If you have the full channel url, there's a resolve url endpoint that will return an object with the id.  

const client = await InnerTube.create()
client.resolveUrl("https://www.youtube.com/@handle")

**Comment by chen-rn** [comment]
ohhh interesting! Thanks!
