### ISSUE TITLE
1.4.2: bug in `#chooseFormat`?

### ISSUE THREAD

**Issue by trullock** [LuanRT/YouTube.js#43]
## Expected Behavior

To be able to choose a format with an audio stream

## Current Behavior

Doesn't choose an apparently valid format

## Failure Information / Steps to Reproduce

Fetch the stream format information for video `onEoq6HGg8k`

See theres a 720p stream with `has_video: true` and `has_audio: true`, this format can't be selected for download because `#chooseFormat` overwrites these properties with it's own interpretation:

```
      format.has_audio = !!format.audioBitrate || !!format.audioQuality;
      format.has_video = !!format.qualityLabel;
```

Presumably this is for some valid use case. However, none of the formats (including the default-chosen 360p which does have an audio stream) has a `audioBitrate` property.

Example format here for the default-chosen 360p stream.
```
		{
			"itag": 18,
			"url": "<snipped for brevity>",
			"mimeType": "video/mp4; codecs=\"avc1.42001E, mp4a.40.2\"",
			"bitrate": 299235,
			"width": 360,
			"height": 360,
			"lastModified": "1643171735824545",
			"contentLength": "3312537",
			"quality": "medium",
			"fps": 25,
			"qualityLabel": "360p",
			"projectionType": "RECTANGULAR",
			"averageBitrate": 298999,
			"audioQuality": "AUDIO_QUALITY_LOW",
			"approxDurationMs": "88630",
			"audioSampleRate": "44100",
			"audioChannels": 2,
			"has_audio": true,
			"has_video": true
		},
```

Why doesnt `#chooseFormat` let me select the `720p` format in this case, is the youtube data wrong, and this overridden `has_audio` property is just the way it is/needs to be, or is this a bug?

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information

**Comment by LuanRT** [comment]
Hi, someone reported a similar problem before. It seems like this is happening because of some outdated code that was needed in previous versions of the library, it should work if this if statement is removed:
https://github.com/LuanRT/YouTube.js/blob/6bdccb89e5bece8daa19961fa415835824ae8aca/lib/Innertube.js#L710

Anyway, it will be fixed in the next released, thanks for reporting.
