### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by inrl-official** [LuanRT/YouTube.js#435]
### Question

Is any way i can get direct url of yutube video from this scrapper, no i get a url but its not possible to fs.writeFilesync or any other methode

### Other details

plz help me

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by itsmenewbie03** [comment]
is downloading a video and writing it on your local drive what you want?
