### ISSUE TITLE
Support 'highest' quality

### ISSUE THREAD

**Issue by trullock** [LuanRT/YouTube.js#45]
## Expected Behavior

To be able to request the `highest` quality available and have it automatically selected

## Current Behavior

Currently you have to mimic the inner workings of `#chooseFormat` in order to replicate this logic and then manually iterate down the potential qualities to see if it exists. This should be encapsulated within the library.

## Sample Code

it would be nice to be able to do this:

```
{
    quality: 'highest'
}
```

**Comment by trullock** [comment]
*activity*

**Comment by Wykerd** [comment]
I'm closing this issue since the above PR implements this suggestion and has been available in the main branch for quite a while now.
