### ISSUE TITLE
YT Music getPlaylist 404

### ISSUE THREAD

**Issue by David-Kurniawan** [LuanRT/YouTube.js#466]
### Question

`await y.music.getPlaylist('RDAMVMHO-31CVnLes')` return 404

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
I'm pretty sure those auto-generated playlists only work on the watch page, at least that's how it is on YouTube.
