### ISSUE TITLE
After create playlist ,Can i get playlist_id??

### ISSUE THREAD

**Issue by speechless42** [LuanRT/YouTube.js#47]
## Question
const ytplaylist = await youtube.playlist.create('hello', ytid);
console.info(ytplaylist);
##
response is 
{ success: true, status_code: 200 }
not
{
  success: boolean, 
  status_code: number, 
  playlist_id?: string 
}
thanks to answer me

**Comment by LuanRT** [comment]
That's because you're using the npm package, which hasn't yet been updated. Try doing `npm install https://github.com/LuanRT/YouTube.js` if you want to try the latest features.

**Comment by speechless42** [comment]
thank you
