### ISSUE TITLE
Add support for returning Track info in metadata

### ISSUE THREAD

**Issue by polds** [LuanRT/YouTube.js#48]
(Apologies for the Rickroll)

It'd be nice if Track info could be surfaced within the metadata object such as what's available in https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by Wykerd** [comment]
By track info, do you mean this section in the description?
![image](https://user-images.githubusercontent.com/45672955/167308397-7fb32062-654a-472e-9a71-5e3127b146ff.png)

**Comment by polds** [comment]
Yes, sorry. That's the music track info I was meaning.
