### ISSUE TITLE
quality in options for download function doesn't work while type is 'videoandaudio'

### ISSUE THREAD

**Issue by ocylib** [LuanRT/YouTube.js#5]
Great job!
```
Innertube.js 
------------------------------------
download(id, options = {}) {
//...
options.type = options.type || 'videoandaudio';  
//...
switch (options.type) {
//...
        default:
          filtered_streams = formats.filter((format) => format.has_video && format.has_audio);
          break;
      }
 }
 if (options.type != 'videoandaudio') {
//...
// the quality option works here,
//but this block only works on type 'audio' or 'video'
}
const selected_format = options.type == 'videoandaudio' ? filtered_streams[0] : URL;
//if type is 'videoandaudio', selected_format  will always be filtered_streams[0], which has video and audio, no matter what quality it is.
}
```
I try to select the format 720p with video and audio,
```
youtube.download(id,{quality: '720p'})
```
it returns itag 18,quality 360p

**Comment by LuanRT** [comment]
Hello,
YouTube usually only provides one format with both video and audio— and it happens to be a low quality format (basically always 360p), so if you don't tell the library what type you want then it'll default to ``videoandaudio`` which always prefers the 360p resolution. If you want to download videos with a higher resolution (>= 720p) you must download the audio separately and then merge it with the video using something like ffmpeg.

**Comment by ocylib** [comment]
get it
