### ISSUE TITLE
1.4.2: Incorrect typing in Trending interface

### ISSUE THREAD

**Issue by shevernitskiy** [LuanRT/YouTube.js#50]
## Expected Behavior

Build and lint project with package without any errors

## Current Behavior

At this moment we have incorrect Trending interface types. It is possible to build and start project localy, but it fails on Heroku (for example)

## Failure Information (for bugs)

```ts
interface Trending {
  now: {
    content:  {
      title: string;
      videos: [];
    }[];
  };
  music: { getVideos: () => Promise<Array>; };
  gaming: { getVideos: () => Promise<Array>; };
  movies: { getVideos: () => Promise<Array>; };
}
```
Function `getVideo()` returns `Promise<Array>`, but Array is generic type. It requires argument like `Array<T>`.
It can be fixed by replacement return value with `Promise<any[]>` i think (if we don't care about exect type)

### Steps to Reproduce

Build typescipt project.

### Failure Logs

Heroku build logs for example:
```
remote: -----> Installing dependencies        
remote:        Installing node modules (yarn.lock)        
remote:        yarn install v1.22.18        
remote:        [1/4] Resolving packages...        
remote:        [2/4] Fetching packages...        
remote:        [3/4] Linking dependencies...        
remote:        [4/4] Building fresh packages...        
remote:        $ tsc -p tsconfig.json        
remote:        node_modules/youtubei.js/typings/index.d.ts(135,37): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).        
remote:        node_modules/youtubei.js/typings/index.d.ts(136,38): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).        
remote:        node_modules/youtubei.js/typings/index.d.ts(137,38): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).        
remote:        error Command failed with exit code 2.        
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information

**Comment by LuanRT** [comment]
Thanks for your report. 
This should be fixed in #44, but since it's still a WIP I'll be pushing a fix later today.

**Comment by shevernitskiy** [comment]
Thank you very much for the quick fix. In the current version, there is a small error too. The property gaming is declared twice. This is also an error for the compiler. Most likely one of them should be renamed to video.

```ts
getTrending(): Promise<{
        now: {
            content: [{
                title: string;
                videos: [];
            }];
        };
        music: {
            getVideos: Promise<any[]>;
        };
        gaming: {
            getVideos: Promise<any[]>;
        };
        gaming: {
            getVideos: Promise<any[]>;
        };
    }>;
```

**Comment by LuanRT** [comment]
> The property gaming is declared twice. This is also an error for the compiler. Most likely one of them should be renamed to video.

My bad, I accidentally renamed the `movies` property to `gaming`. Should be fixed now. 
Thanks!
