### ISSUE TITLE
Can I choose which transcript to download in the function getTranscript()?

### ISSUE THREAD

**Issue by RadoslavL** [LuanRT/YouTube.js#501]
### Question

If I have the name of the captions I want to get (like "English (auto-generated)"), can I select these captions to be downloaded? The only argument to the getTranscript() function is the video ID.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [x] I have provided sufficient information.

**Comment by inad9300** [comment]
My two cents, in case it helps:
```
const videoInfo = await innertube.getInfo(videoId)
const captions = videoInfo.captions?.caption_tracks ?? []
const englishCaptions = captions.filter(cc => cc.language_code === 'en' || cc.language_code?.startsWith('en-'))
const manualEnglishCaptions = englishCaptions.filter(cc => cc.kind !== 'asr' && !cc.name.text?.includes('auto-generated')) 
const englishCaptionsUrl = manualEnglishCaptions[0]?.base_url ?? englishCaptions[0]?.base_url // Prefer handcrafted transcripts
const captionsDom = parseHtml(await fetch(englishCaptionsUrl).then(res => res.text())) // Use JSDOM or similar to parse.
```

**Comment by RadoslavL** [comment]
Thank you!
