### ISSUE TITLE
Download quality options

### ISSUE THREAD

**Issue by Alexloof** [LuanRT/YouTube.js#504]
### Question

Is there a way of specifying the `quality` option for `download` so that it grabs the best quality video but not higher than `1080p`?

Today I am using this but that can give me really large videos:
```
    const stream = await yt.download(id, {
      format: 'mp4',
      quality: 'bestefficiency',
      type: 'video',
    })
```

Using this gives me error if the youtube video doesn't have a 1080p stream:
```
    const stream = await yt.download(id, {
      format: 'mp4',
      quality: '1080',
      type: 'video',
    })
```

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by willemmulder** [comment]
I think Youtube itself does also not support that natively, so you'd probably have to resort to a process where you try the 1080p first, then try 720p, and so on until there is a stream that works?

**Comment by willemmulder** [comment]
Also, you can check the available formats upfront, using the information from the `.getInfo()` call.

**Comment by Alexloof** [comment]
Thanks for the response @willemmulder 

Yea, that's the approach I decided to go with. 

(I think I have seen some fancy syntax in other youtube download libraries where you can set a limit, so I thought that was something that was provided from somewhere).

You are welcome to close the issue if you don't think it make sense to include in the library.
