### ISSUE TITLE
6.4.1 - Downloading a live stream always stops after a few chunks

### ISSUE THREAD

**Issue by willemmulder** [LuanRT/YouTube.js#518]
### Steps to reproduce

```
const videoId = '...'; // Some livestream
const data = await youtube.getBasicInfo(videoId);
const stream = await data.download({
    type: 'audio', // same result for video or video+audio
    quality: 'best', 
    format: 'mp4',
});
const file = createWriteStream(`test.m4a`);
for await (const chunk of Utils.streamToIterable(stream)) {
    console.log('Write!');
    file.write(chunk);
}
```

Consistently after five 'Write!' logs, it stops and no more data is written to the file.

### Failure Logs

```shell
Write!
Write!
Write!
Write!
Write!
```

### Expected behavior

I expect the stream to keep up with the livestream and keep on yielding chunks whenever they become available.

### Current behavior

It consistently stops after five chunks. 

I'm totally unsure, but maybe the chunksize in the download function is too large (10Mb) for live streaming?

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
The download function is designed for downloading normal videos, not live streams. Live streams function completely differently and also require post-processing with ffmpeg. Unlike normal videos, where you request chunks of the same file, live streams are made up of lots different usually 5 second long files, so you can't just append the segments together.
You need to extract the audio and video data from each of those files and stitch them together into a single file.

**Comment by absidue** [comment]
Also the reason you get the same thing if you do `audio+video` and `audio` is that live streams only provide separate audio and video files (only normal videos have the combined 360p and 720p formats), so you need to download them separately.

**Comment by absidue** [comment]
Passing the HLS URL to ffmpeg and letting that do all the stuff might work better.

**Comment by willemmulder** [comment]
@absidue Thanks! 

I managed to make it (somewhat) work by fetching and parsing the `data.streaming_data.hls_manifest_url`. Then extracting a specific m3u from there, and then running that through `node-m3u8stream` to turn it into a stream.

The only problem is that I only need audio, but it seems I can only select video formats in the m3u. 

Maybe I'll just try and continuously fetch the 5-second audio chunk coming from the below URL and then stitch it together somehow. 

```
const format = data.chooseFormat({ type: 'audio', quality: 'best' });
const url = format?.decipher(youtube.session.player);
```

Will be continued, but for now Issue closed!
