### ISSUE TITLE
Downloadable links

### ISSUE THREAD

**Issue by CoDe-er1** [LuanRT/YouTube.js#52]
I want to request for the new feature that is to exact the downloadable link of the YouTube video for example:

A YouTube video link https://youtu.be/qI-A_larCGE

A downloadable link of it https://rr3---sn-h5576nss.googlevideo.com/videoplayback?expire=1652288957&ei=XZl7YqqmC_2xlu8PuMiEOA&ip=216.151.180.183&id=o-ADUDO8j8uQSTxVHiZSHBETmCL7GDTVVgu_Sm3Gm2JiSJ&itag=22&source=youtube&requiressl=yes&spc=4ocVC9nutYHsjkCYiBgvDbglzj-E&vprv=1&mime=video%2Fmp4&ns=79TMJKSzq12BhbX_enzNYNoG&cnr=14&ratebypass=yes&dur=725.112&lmt=1650523739703305&fexp=24001373,24007246&c=WEB&txp=5532434&n=R9O0uWogCvtjcQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgL20sGxSUTmD32Tx3S5VK3fSX3PxP-mGPKsLk_ncKZMUCIDJytb1Y95tfHe_wv-DfsBxDHtP-YkczzpZScteExSYk&title=12%20TRANSFORMING%20PARKING%20GARAGES%20OF%20THE%20NEXT%20LEVEL&rm=sn-ab5eek76&req_id=8d6f82d224eba3ee&cm2rm=sn-4pcxgfvgaq-3uhe7l,sn-fapo3ox25a-3uh6ee&redirect_counter=3&cms_redirect=yes&cmsv=e&ipbypass=yes&mh=Mg&mip=103.148.23.161&mm=30&mn=sn-h5576nss&ms=nxu&mt=1652267315&mv=m&mvi=3&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgLqZoCFNn4hxQ_yFAzZ0uVsboVufMABSNsPmuWm-2sV0CIQDxZMK5d6rYaMo0j3xqN21Bm3bmRemKRjQLmQ7rx1B7Fw%3D%3D

**Comment by shevernitskiy** [comment]
This is downloadable link:)
Youtube provide data as streams. You can download this data.

Example with axios:
```ts
axios
  .get(streamUrl, {
    responseType: 'stream',
    headers: { Range: 'bytes=0-' }
  })
  .then(({ data }) => {
    data.pipe(fs.createWriteStream('myfile.mp4'))
  })
  .catch((err) => {
    console.log(err)
  })
  ```

**Comment by CoDe-er1** [comment]
I not mean by that

**Comment by shevernitskiy** [comment]
I gave you an exmaple to download links like you gave in your exmaple. That is url to stream. You should download it as stream.

**Comment by CoDe-er1** [comment]
Sry but I don't want to download it I just want to get the link.

**Comment by CoDe-er1** [comment]
Is there any way to get the link of any video?

**Comment by shevernitskiy** [comment]
If you want have a link to a file, you should save stream as file first. And then host it somewhere.

**Comment by CoDe-er1** [comment]
I guess you didn't understand what I mean
Basically, YouTube store a video to Google video.com and whenever someone watch video the YouTube get the video through that Google video.com domain URL and the video is kinda public so, I want to get that like like

A YouTube video link:  https://youtu.be/qI-A_larCGE

that video is stored by YouTube to here : 
https://rr3---sn-h5576nss.googlevideo.com/videoplayback?expire=1652288957&ei=XZl7YqqmC_2xlu8PuMiEOA&ip=216.151.180.183&id=o-ADUDO8j8uQSTxVHiZSHBETmCL7GDTVVgu_Sm3Gm2JiSJ&itag=22&source=youtube&requiressl=yes&spc=4ocVC9nutYHsjkCYiBgvDbglzj-E&vprv=1&mime=video%2Fmp4&ns=79TMJKSzq12BhbX_enzNYNoG&cnr=14&ratebypass=yes&dur=725.112&lmt=1650523739703305&fexp=24001373,24007246&c=WEB&txp=5532434&n=R9O0uWogCvtjcQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgL20sGxSUTmD32Tx3S5VK3fSX3PxP-mGPKsLk_ncKZMUCIDJytb1Y95tfHe_wv-DfsBxDHtP-YkczzpZScteExSYk&title=12%20TRANSFORMING%20PARKING%20GARAGES%20OF%20THE%20NEXT%20LEVEL&rm=sn-ab5eek76&req_id=8d6f82d224eba3ee&cm2rm=sn-4pcxgfvgaq-3uhe7l,sn-fapo3ox25a-3uh6ee&redirect_counter=3&cms_redirect=yes&cmsv=e&ipbypass=yes&mh=Mg&mip=103.148.23.161&mm=30&mn=sn-h5576nss&ms=nxu&mt=1652267315&mv=m&mvi=3&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgLqZoCFNn4hxQ_yFAzZ0uVsboVufMABSNsPmuWm-2sV0CIQDxZMK5d6rYaMo0j3xqN21Bm3bmRemKRjQLmQ7rx1B7Fw%3D%3D

**Comment by shevernitskiy** [comment]
Oh, i got it. You just want short url to video? Sorry, my bad:)
At least yYou could use full link pattern and id of the video
```ts
https://www.youtube.com/watch?v={$id}
```

**Comment by CoDe-er1** [comment]
still you didn't understand :/

**Comment by CoDe-er1** [comment]
By the way it returns error,
const youtube = require('youtubei.js')
(async() => {
  const video = await youtube.getDetails('C5obeRhGOX0')
  console.log(video)
})();
