### ISSUE TITLE
InnertubeError: Comments page did not have any content.<version> <title>

### ISSUE THREAD

**Issue by yashb042** [LuanRT/YouTube.js#521]
### Steps to reproduce

While commenting on a video, the comments were working fine until last week. Now getting this error.

Simple code - 

```
 await yt.session.signIn(creds);

    const comment_section = await yt.getComments(video_id);

    console.info(`This video has ${comment_section.header?.comments_count.toString() || 'N/A'} comments.\n`);

    await comment_section.createComment(content_to_post);
```

### Failure Logs

```shell
InnertubeError: Comments page did not have any content.
    at new Comments (/Users/yash.bansal/workspace/YouComment/node/node_modules/youtubei.js/src/parser/youtube/Comments.ts:29:13)
    at Innertube.<anonymous> (/Users/yash.bansal/workspace/YouComment/node/node_modules/youtubei.js/src/Innertube.ts:192:12)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yash.bansal/workspace/YouComment/node/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  date: 2023-10-11T03:22:16.442Z,
  version: '6.4.1'
```

### Expected behavior

The comment to be posted on youtube

### Current behavior

Getting the above exception

### Version

Edge

### Anything else?

Using latest version - 6.4.1

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by yashb042** [comment]
Any updates on this?

**Comment by LuanRT** [comment]
Are you getting this error for every video? It's coming from this line: https://github.com/LuanRT/YouTube.js/blob/e02139532b2c07aaf72dd1bd8610f63b6780001d/src/parser/youtube/Comments.ts#L28-L29 And means YouTube returned a response without any relevant content. Not a lot we can do about it without knowing how you are using the library.

**Comment by yashb042** [comment]
I'm getting this error - 

`InnertubeError: Request to https://www.youtube.com/youtubei/v1/comment/create_comment?prettyPrint=false&alt=json failed with status 400
    at HTTPClient.<anonymous> (/Users/yash.bansal/workspace/YouComment/node/node_modules/youtubei.js/src/utils/HTTPClient.ts:145:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yash.bansal/workspace/YouComment/node/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  info: '{\n' +
    '  "error": {\n' +
    '    "code": 400,\n' +
    '    "message": "Request contains an invalid argument.",\n' +
    '    "errors": [\n' +
    '      {\n' +
    '        "message": "Request contains an invalid argument.",\n' +
    '        "domain": "global",\n' +
    '        "reason": "badRequest"\n' +
    '      }\n' +
    '    ],\n' +
    '    "status": "INVALID_ARGUMENT"\n' +
    '  }\n' +
    '}\n',
  date: 2023-11-01T17:41:22.454Z,
  version: '7.0.0'
}`


I'm using it like this 

`    const comment_section = await yt.getComments(video_id);

    console.info(`This video has ${comment_section.header?.comments_count.toString() || 'N/A'} comments.\n`);

    await comment_section.createComment(content_to_post);`
