### ISSUE TITLE
Proxy server being blocked by Google Server

### ISSUE THREAD

**Issue by jahwin** [LuanRT/YouTube.js#525]
### Question

I have successfully set up a proxy server to redirect all YouTube.js and web requests to my server, and everything is functioning perfectly for regular video content. However, I've encountered an issue when it comes to HLS live streaming.

Here are the specifics:

I retrieve the HLS link from the streamData and pass the URL to the Shaka Player. Everything works seamlessly when my proxy server is running locally. However, when I migrate the server to an online environment hosted on Digital Ocean, Google appears to block the manifest links for live streams, while video content continues to work without any issues.

I'm looking for advice on how to prevent Google from blocking my requests originating from the proxy server.

<img width="1353" alt="Screenshot 2023-10-18 at 05 13 32" src="https://github.com/LuanRT/YouTube.js/assets/31317808/ba02f874-46a0-40ea-b4c0-c468f7100c4e">

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LAKSHYAJAIN16** [comment]
same problem. any workaround?
