### ISSUE TITLE
No error handler for refreshAccessToken function in OAuth.js

### ISSUE THREAD

**Issue by WalterWoshid** [LuanRT/YouTube.js#564]
### Steps to reproduce

1. Create your OAuth Credentials (type "offline")
2. Wait for the `expires` value to expire
3. Sign in to innertube

I know that it automatically should update the `refresh_token`, but for some reason I receive an `Unauthorized` error, but the code runs successfully as if there was no error.

![image](https://github.com/LuanRT/YouTube.js/assets/36635504/08ee4cbe-76c9-4334-b004-e1de7ff405f4)
![image](https://github.com/LuanRT/YouTube.js/assets/36635504/116df689-0f39-4ea3-86b1-8e8b519d9d7a)
![image](https://github.com/LuanRT/YouTube.js/assets/36635504/a2951697-d006-4a04-a339-731bd3e83cb1)

### Failure Logs

```shell
No Failure Logs
```

### Expected behavior

Error

### Current behavior

Runs successfully as if there was no error

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by WalterWoshid** [comment]
Also, not sure why this happens, but the initial requests on innertube (like `innertube.getHomeFeed()`) work successfully once signed in with my generated OAuth2 Credentials, but after the `expires` field expired, I received the `unauthorized_client` error. Not sure how to fix this from my side.

**Comment by LuanRT** [comment]
Would you be able to check what the `getClientIdentity` function is returning for you and report back here? Maybe I can reproduce this issue on my side.

**Comment by LuanRT** [comment]
Alrighty, thanks for the extra context @WalterWoshid! I think one way to solve this would be by adding a way to pass in your own client id and client secret to the `Session#signIn` function. Would that work for you?

**Comment by WalterWoshid** [comment]
Sounds good :)

Btw, great library, love it. Was at first thinking in building it myself for PHP, but quickly failed, because I tried to pass the cookies of YouTube, but after 5 minutes I always received a "Your YouTube history is off" and gave up. Didn't know that you can fetch the content from their website with OAuth2 though. Plus the type support is great!

I will create an issue for the YouTube TV client then for the failing request.
