### ISSUE TITLE
8.2.0 getPlaylist not returns full result

### ISSUE THREAD

**Issue by kms0219kms** [LuanRT/YouTube.js#575]
### Steps to reproduce

Use this simple code to reproduce:
```ts
import { Innertube, UniversalCache } from 'youtubei.js';

const yt = await Innertube.create({
  cache: new UniversalCache(false)
});

async function main(id: string) {
  const playlist = await yt.getPlaylist(id)
  console.log("videos =>", playlist.videos)
  console.log("total =>", playlist.videos.length)
  return playlist
}

main(<VALID_PLAYLIST_ID>)
```

### Failure Logs

```shell
videos => [....(too long to paste here)]
total => 100
```

### Expected behavior

It should return the length of video tracks in the playlist.

### Current behavior

If the original playlist has over 100 videos, it only gives the first 100 videos.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by kms0219kms** [comment]
It can be used with this method:

1. For the initial request, get first data from `contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.sectionListRenderer.contents[0].itemSectionRenderer.contents[0].playlistVideoListRenderer.contents` as usual,

2. Get pagination token from `contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.sectionListRenderer.contents[1].continuationItemRenderer.continuationEndpoint.continuationCommand.token`, and use this value in `continuation` key in new request,

3. Get more data from `onResponseReceivedActions[0].appendContinuationItemsAction.continuationItems`,

4. and get pagination token from `onResponseReceivedActions[0].appendContinuationItemsAction.continuationItems[100].continuationItemRenderer.continuationEndpoint.continuationCommand.token` and repeat from 3, with `continuation` key from this step.

**Comment by absidue** [comment]
This isn't a bug, YouTube.js and your code is doing exactly what it should do, your code doesn't tell YouTube.js to get the continuations, all you are doing is fetching the initial playlist response.

From your next message it also seems like you haven't looked at the auto-complete in your code editor or the docs.

As mentioned in the README.md (https://github.com/LuanRT/YouTube.js#getplaylistid) `getPlaylist` returns a `Playlist` object, which inherits from `Feed` and if you follow the link through to the `Feed` docs (https://github.com/LuanRT/YouTube.js/blob/main/docs/API/feed.md), you'll notice the `has_continuation` getter and `getContinuation` method.

Here is some code that will fetch the entire playlist.
```js
import { Innertube, UniversalCache } from 'youtubei.js';

const yt = await Innertube.create({
  cache: new UniversalCache(false)
});

async function main(id: string) {
  const videos = []
  const playlist = await yt.getPlaylist(id)
  videos.push(...playlist.items)

  // Not overwriting the playlist variable, so that you can still get the playlist metadata like the title from it
  let page = playlist
  while (page.has_continuation) {
    page = await page.getContinuation()
    videos.push(...page.items)
  }

  console.log("videos =>", videos)
  console.log("total =>", videos.length)
  return playlist
}

main(<VALID_PLAYLIST_ID>)
```

**Comment by kms0219kms** [comment]
Thank you for your code snippet! This really helped us :) Happy new year!
