### ISSUE TITLE
8.2.0 Playlist videos contain videos not in playlist

### ISSUE THREAD

**Issue by iBicha** [LuanRT/YouTube.js#578]
### Steps to reproduce

Some playlists can have a "Recommended" videos section after playlist videos.

Since Playlist class inherits from a Feed, and the `videos` will try to find all video nodes, the recommended videos end up in the playlist, which is not a desired behaviour

<img width="1045" alt="Screen Shot 2024-01-12 at 4 12 04 PM" src="https://github.com/LuanRT/YouTube.js/assets/17722782/13542680-ba65-4b81-974d-a82ad3e0989f">

### Failure Logs

```shell
No failure
```

### Expected behavior

`Playlist.videos` should override the Feed behaviour to include only the videos from the actual playlist.
Recommended should be a separate field.

Edit: maybe `Playlist.videos` can return all videos, but `Playlist.items` should return only playlist videos

### Current behavior

Playlist videos + recommended are returned.

### Version

Default

### Anything else?

Yes, this Recommended stuff is new to me, and does not appear on all playlists.
Also, this playlist has recommended videos and recommended playlists.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
I'd say that `.video` is behaving as expected, by returning all videos on the page, `.items` is the one that is behaving unexpectedly in this situation, because that specifically says that it returns the playlist's items.

> Returns the items of the playlist.

https://github.com/LuanRT/YouTube.js#getplaylistid

**Comment by LuanRT** [comment]
Strange.. I think you need to fetch additional continuations to get those sections (in our case, there's no way to tell it apart  from a normal playlist continuation until `getContinuation` is called because it just appears as a normal `ContinuationItem` inside the `SectionList` node).
```js
[
  ItemSection {
    type: 'ItemSection',
    header: null,
    contents: [ [PlaylistVideoList] ] // The actual content of the playlist is here.
  },
  ContinuationItem { // If the playlist is large then this'll be a normal continuation, otherwise it returns the recommendation sections instead.
    type: 'ContinuationItem',
    trigger: 'CONTINUATION_TRIGGER_ON_ITEM_SHOWN',
    endpoint: NavigationEndpoint {
      type: 'NavigationEndpoint',
      payload: [Object],
      metadata: [Object]
    }
  }
]
```

**Comment by iBicha** [comment]
I was using this playlist https://www.youtube.com/playlist?list=PLjV0EBqFSCxZDx4V4hmmWAlBg0Y8K7n-m
interestingly enough, if I use my account, I see recommended videos and playlists.
Without an account, I only see the recommended playlists.

**Comment by LuanRT** [comment]
https://github.com/LuanRT/YouTube.js/pull/579

Ok. I think I managed to fix this, here's the PR if you guys want to review & test it.

**Comment by absidue** [comment]
> interestingly enough, if I use my account, I see recommended videos and playlists.
Without an account, I only see the recommended playlists.

When you are logged in and viewing your own playlist, YouTube is presumably showing you stuff that you can add to the playlist. When you are logged out, you can't modify any playlists, so instead they display other pre-made playlists that you might like.
