### ISSUE TITLE
chat-update event is not working

### ISSUE THREAD

**Issue by technoeren13** [LuanRT/YouTube.js#58]
Hi! I want to track stream message but chat-update event is not working.

![image](https://user-images.githubusercontent.com/48402602/170832088-37d89514-5ffa-4593-a6b1-23787562b7e5.png)

**Comment by LuanRT** [comment]
Hi there, does it throw any error message?

**Comment by technoeren13** [comment]
> 

Any error messages etc. I'm not buying. The direct doesn't work, it doesn't return anything.

**Comment by LuanRT** [comment]
Just tried it on [runkit](https://npm.runkit.com/youtubei.js) and it seems to be working as expected:
![Screenshot_20220529-013613](https://user-images.githubusercontent.com/30878106/170852455-25d8ae10-756c-4ea5-8799-f6f41a8b769b.png)

It's really hard to pinpoint what is causing this as it seems to be an isolated case, but I'll do some more testing.

**Comment by technoeren13** [comment]
![image](https://user-images.githubusercontent.com/48402602/171235549-d3fd9312-7490-4546-abbf-3a413c4b4691.png)

it was working yesterday but not now. But updating video stats is working.

**Comment by technoeren13** [comment]
I understand problem. If the clock is back it doesn't work.

**Comment by technoeren13** [comment]
I understand this problem. If the clock is back it doesn't work.
