### ISSUE TITLE
getChannel().getVideos() method doesnt work in some channels

### ISSUE THREAD

**Issue by rizer234** [LuanRT/YouTube.js#601]
### Steps to reproduce

Chill Beat channel with channel_id = "UC_oeV58JVVXtxxs09oK1dLg"
when we call getChannel().getVideos(), returns just one video but channel has 78 videos.

### Failure Logs

```shell
in result.current_tab.content result is:


RichGrid {
  type: 'RichGrid',
  header: FeedFilterChipBar {
    type: 'FeedFilterChipBar',
    contents: [ [ChipCloudChip], [ChipCloudChip], [ChipCloudChip] ]
  },
  contents: [
    RichItem { type: 'RichItem', content: [Video] },
    ContinuationItem {
      type: 'ContinuationItem',
      trigger: 'CONTINUATION_TRIGGER_ON_ITEM_SHOWN',
      endpoint: [NavigationEndpoint]
    }
  ]
}


while videos list in content is one video
```

### Expected behavior

expected presents all of videos in page one.

### Current behavior

just one video in contents:

> [
>   RichItem {
>     type: 'RichItem',
>     content: Video {
>       type: 'Video',
>       id: '6LHVpSKoXfI',
>       title: [Text],
>       description_snippet: [Text],
>       expandable_metadata: null,
>       thumbnails: [Array],
>       thumbnail_overlays: [Array],
>       rich_thumbnail: [Array],
>       author: [Author],
>       badges: [],
>       endpoint: [NavigationEndpoint],
>       published: [Text],
>       view_count: [Text],
>       short_view_count: [Text],
>       duration: [Object],
>       show_action_menu: false,
>       is_watched: false,
>       menu: [Menu]
>     }
>   },
>   ContinuationItem {
>     type: 'ContinuationItem',
>     trigger: 'CONTINUATION_TRIGGER_ON_ITEM_SHOWN',
>     endpoint: NavigationEndpoint {
>       type: 'NavigationEndpoint',
>       payload: [Object],
>       metadata: [Object]
>     }
>   }
> ]

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Can't reproduce it on my side unfortunately. What happens if you try to fetch the continuation (`Channel#getContinuation()`)?
```ts
Tab {
  type: 'Tab',
  title: 'Videos',
  selected: true,
  endpoint: NavigationEndpoint {
    type: 'NavigationEndpoint',
    payload: {
      browseId: 'UC_oeV58JVVXtxxs09oK1dLg',
      params: 'EgZ2aWRlb3PyBgQKAjoA',
      canonicalBaseUrl: '/@chillbeatphonk'
    },
    metadata: {
      url: '/@chillbeatphonk/videos',
      page_type: 'WEB_PAGE_TYPE_CHANNEL',
      api_url: 'browse'
    }
  },
  content: RichGrid {
    type: 'RichGrid',
    header: FeedFilterChipBar { type: 'FeedFilterChipBar', contents: [Array] },
    contents: [
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [RichItem],         [RichItem],
      [ContinuationItem]
    ]
  }
}
```

**Comment by rizer234** [comment]
in await getChannel(id).videos works right, but if:

> channelSession = await innertube.getChannel(id)
> videos = await channelSession.getVideos()

in this case number of videos is 1.
it have a pagination token and continuation but second page is the same but with 4,5 videos and likewise, as far as sum of number of all pages videos are 7,8

**Comment by rizer234** [comment]
oh i undrestood!
it because enable_safety_mode in Innertube config was true!
i chenged it to false and represented all videos!
