### ISSUE TITLE
v9.0.2-deno Request to https://www.youtube.com/youtubei/vtrue/player?key=[REDACTED]&prettyPrint=false&alt=json failed with status 400

### ISSUE THREAD

**Issue by mnsrulz** [LuanRT/YouTube.js#604]
### Steps to reproduce

getBasicInfo is always throwing 400 error

```
import { Innertube } from "https://deno.land/x/youtubei@v9.0.2-deno/deno.ts";
const youtube = await Innertube.create();
const ytid = 'TIQ5hrfermg'

Deno.serve(async (req: Request) => {
    try {
        const metadata = await youtube.getBasicInfo(ytid, 'iOS');
        return new Response(metadata);
    } catch (err) {
        return new Response(err.message);
    }    
});
```

### Failure Logs

```shell
n/a
```

### Expected behavior

Should return the appropriate information about the youtube id

### Current behavior

Erroring out with 400 bad request error

### Version

Edge

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Fixed in https://github.com/LuanRT/YouTube.js/commit/2068dfb73eefc0e40157421d4e5b4096c0c8429c.

**Comment by jason-hwang** [comment]
awesome!!
