### ISSUE TITLE
How to read live streams?

### ISSUE THREAD

**Issue by willemmulder** [LuanRT/YouTube.js#610]
### Question

I want to read the audio of a live stream. So what I currently do is

    const data = await youtube.getBasicInfo(videoId);
    const format = data.chooseFormat({ type: 'audio', quality: 'best' });
    const url = format?.decipher(youtube.session.player);

Then fetch that data (which is a chunk of 4 seconds of audio) and repeat the process every so many seconds.

It feels quite cumbersome haha. Is there a better way? 

Thanks!

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by willemmulder** [comment]
Please keep it open. And would be nice to not auto-close issues when there has not been a follow-up from the authors yet.

**Comment by willemmulder** [comment]
Keeping it open. @LuanRT Do you have any insights on this?

**Comment by absidue** [comment]
@willemmulder Nobody is looking into this other than you, everyone else just uses the DASH manifests provided by YouTube instead of building a custom solution. So you are probably the expert on the subject.

Also as this isn't directly related to YouTube.js, I'm not sure why you were expecting anyone to follow up on it, definitely not worth unnecessarily pinging someone.

**Comment by willemmulder** [comment]
@absidue Okay, that's some unnecessary assumptions. 

It is a Youtube.js issue, because right now the lib doesn't support livestreams (afaik) so it's a feature request. That's what these issues are for, right? Luan would be more than welcome to say that livestreaming support is not planned. Until that moment, I keep the issue open and people are welcome to join and/or share their solution. Just saying "you're the only one" doesn't help any one.

But I'd love to learn about how other people use the DASH / HLS manifests provided by Youtube. I can't seem to find anything about it?

**Comment by absidue** [comment]
@willemmulder All the information you need to know is in the comments that I left on the other issue that you opened and seem to have forgotten about.

https://github.com/LuanRT/YouTube.js/issues/518

**Comment by willemmulder** [comment]
Yeah will admit that I forgot about that one. But either way it doesn't really make livestreams possible for me. Would be nice if we had 'native' functionality in Youtube.js for reading livestreams. I had to give up the current approach, because Youtube sometimes gives me the same 4 second chunk repeatedly and then suddenly skips a chunk, which makes it impossible to get a smooth audio stream.

**Comment by absidue** [comment]
Sounds like you need to adjust your timer, because YouTube can't give you the next chunk before it exists, it's a live stream after all. Also not sure what functionality you want in YouTube.js for it, YouTube's live stream chunks are self-initialising, which means each one is effectively it's own separate file. So it would require a completely separate download function, than the existing one, where the user is aware that they have to write each chunk into a separate file and then use an external tool like ffmpeg to stich them together.

Or you could just go the much simpler route and just pass the DASH or HLS manifest to your player.

**Comment by absidue** [comment]
Additionally you aren't meant to be sitting right at the live edge, YouTube's own player sits 3 chunks behind the live edge (YouTube helpfully tells you that in the API response), which gives it time to download the new ones, so you get smooth playback.

**Comment by willemmulder** [comment]
Thanks! Just to share my approach, I tried two things: both HLS based, and audio-stream based. 

The HLS version doesn't work because Google prohibits me from downloading the manifest. I always get "You're a robot" or something similar, after I deploy. Maybe bad luck with the server IP or maybe I miss something in setting specific parameters on the URL that would make this work.

The audio-stream version doesn't work because with that approach you can only read the chunk 'at the live edge'. In theory that should yield the next chunk every 4 seconds, but in practice it's very unpredictable, where I often miss chunks. I haven't figured out a way to specifically target/download a 'historic chunk', i.e. trying to sit behind the live edge and target chunks specifically.

```
// Note: this does currently NOT work, because fetching the manifest from Google always returns an error from Google that a robot is trying to access the page
// Very annoying
const createYoutubeVideoStream = async (videoInfo:VideoInfo) => {
    // Validate
    if (!videoInfo) {
        throw new Error('No video info provided');
    }
    const manifestURL = videoInfo.streaming_data?.hls_manifest_url;
    if (!manifestURL) {
        throw new Error('No playlist URL found');
    }
    return await createm3uStreamForURL(manifestURL);
}

// Note: drawback of Audio Stream is that we have just one audioStreamURL, which yields a new chunk every so many seconds
// However, it sometimes misses a chunk, which means we have 5 secs of missing audio
// We try to fix that by reading very often, but that's quite wasteful
// Note 2: this ONLY works with live videos, because they are the only ones that have unmuxed sources
export class YoutubeAudioStream extends Readable {

    READINTERVAL = 300;
    MAX_EMPTY_CHUNKS = 20; // If we encounter 20 empty chunks in a row, we assume the stream is over

    streamURL:string;
    previousChunks:ArrayBuffer[] = [];
    interval:NodeJS.Timeout | null = null;
    emptyChunkCount = 0;

    constructor(streamURL:string, options = {}) {
        super({ ...options, highWaterMark: 512 * 1024 }); // 512KB
        this.streamURL = streamURL;
        this.interval = null;
    }

    _read() {
        const readData = async () => {
            try {
                if (this.readableLength < this.readableHighWaterMark) {
                    let response = await fetch(this.streamURL);
                    let chunk = await response.arrayBuffer();
                    if (chunk.byteLength == 0) {
                        console.log('encountering empty chunk, so re-reading');
                        this.emptyChunkCount++;
                        if (this.emptyChunkCount > this.MAX_EMPTY_CHUNKS) {
                            console.log('encountering too many empty chunks, so ending stream');
                            this.push(null);
                            return;
                        }
                        readData();
                        return;
                    }
                    // Reset empty chunk count
                    this.emptyChunkCount = 0;
                    // Check if chunk is not in previousChunks
                    // Somehow, sometimes we get the same chunk twice, so we need to check for that
                    if (!this._isChunkInPreviousChunks(chunk)) {
                        console.log('pushing chunk', chunk.byteLength);
                        // Add chunk to previousChunks and ensure it only keeps the last 10
                        this.previousChunks.push(chunk);
                        if (this.previousChunks.length > 10) {
                            this.previousChunks.shift();
                        }
                        this.push(Buffer.from(chunk));
                    } else {
                        console.log('skipping identical chunk');
                    }
                } else {
                    console.log('skipping read due to buffer size!');
                }
            } catch (error) {
                console.log('Error!', error);
                //this.emit('error', error);
            }
        };
        if (!this.interval) {
            // Read every second, so we don't miss any data
            this.interval = setInterval(readData, this.READINTERVAL);
            readData(); // Read immediately on the first _read() call
        }
    }

    _destroy() {
        if (this.interval) {
            clearInterval(this.interval);
            this.interval = null;
        }
    }

    _isChunkInPreviousChunks(newChunk:ArrayBuffer) {
        return this.previousChunks.some(previousChunk => this._compareChunks(previousChunk, newChunk));
    }

    _compareChunks(chunk1:ArrayBuffer, chunk2:ArrayBuffer) {
        return chunk1.byteLength === chunk2.byteLength && new Uint8Array(chunk1).every((value, index) => value === new Uint8Array(chunk2)[index]);
    }
}
```

PS: at least for the audiostream, I did not have to process anything with ffmpeg or similar. I could just stitch them together and that works, thankfully.
