### ISSUE TITLE
Add support for new comment section structure 

### ISSUE THREAD

**Issue by LuanRT** [LuanRT/YouTube.js#613]
### Describe your suggestion

Looks like the comment nodes need to be updated using the mutation data found in the `frameworkUpdates` field. Each node has an id that can be used to identify its respective mutation.

### Other details

We already handle some mutation data for YTMusic, so it shouldn't be difficult to do the same for YouTube.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
I have all the code for it already, I've worked on this in the last few days. Both for the comments and rewriting the attributed text handling so it can handle styling and emojis.

**Comment by absidue** [comment]
I can create pull requests for both, I'm sorry that I haven't already done it yet.

**Comment by LuanRT** [comment]
Oh that's lovely then! I was working on it as well, but since you already have it all prepared then feel free to submit your PRs. I'll review them right away.

**Comment by absidue** [comment]
#614 handles the new CommentView nodes, it doesn't support the logged in only features such as leaving a reply or liking a comment, feel free to push commits to the pull request if you want to build on top of my changes.

#615 Refactors the attributed text handling, to support formatting and custom emojis, I've provided some examples in the pull request.
