### ISSUE TITLE
9.1.0 Video "the following content is not available on this app" returned with Android

### ISSUE THREAD

**Issue by iBicha** [LuanRT/YouTube.js#623]
### Steps to reproduce

```
const yt = await Innertube.create();
const videoInfo = await yt.getInfo('v', 'ANDROID');
const dash = await videoInfo.toDash();
```
Then play the dash somewhere

### Failure Logs

```shell
N/A
```

### Expected behavior

Returns a dash to the video stream

### Current behavior

Returns a video that says "the following content is not available on this app"

### Version

Default

### Anything else?

Same as https://github.com/iv-org/invidious/issues/4498

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by wukko** [comment]
all requests with `ANDROID` client get redirected to `aQvGIIdgFDM` video, hence the different "content not available" video:

<img width="432" alt="image" src="https://github.com/LuanRT/YouTube.js/assets/71202418/29cd50a2-37d3-4aa8-a089-b4c775067b4a">


can be worked around by using `YTMUSIC_ANDROID` client instead, but it's just the matter of time before youtube updates that one too.

**Comment by absidue** [comment]
@iBicha The solution it to not use the Android client anymore (we should probably remove support for it from the library), switch to use one that actually works.

The android client now requires you to send along a valid DroidGuard result with the requests, which YouTube.js has no way to do, unless you want to run and Android device and extract that DroidGuard results from it for every single request you do.

**Comment by absidue** [comment]
@iBicha For the code snippet you provided the WEB client, which is the default when you don't force anything else, works just fine. Just remove the `"ANDROID"` string from your code.

**Comment by LuanRT** [comment]
> @iBicha For the code snippet you provided the WEB client, which is the default when you don't force anything else, works just fine, as long as you use a real video ID of course. Just remove the `"ANDROID"` string from your code.

After a few rounds of debugging it seems that if you send the player payload encoded as protobuf and without the DroidGuard bytes, you can still get video info and streaming data (but if you are not logged in, the streaming data formats will all start returning 403 after a while, same behavior we had before using those special parameters).

So I'm guessing we could keep the Android client for those that use the library with an account.

**Comment by iBicha** [comment]
@LuanRT Amazing, that seems to work well!

**Comment by LuanRT** [comment]
@iBicha Great, thanks for testing :). Closing this as completed for now.

**Comment by Croodo** [comment]
This was fixed, but happening again. but this time not the all time, sometimes video works.
