### ISSUE TITLE
Android client

### ISSUE THREAD

**Issue by Elite** [LuanRT/YouTube.js#625]
### Question

While testing the ```ANDROID``` client with new values I can still not get the 720p format under the ```streamingData``` json as earlier? If I add the ```X-GOOG-API-FORMAT-VERSION``` header the request does not go through.

What am I missing here? 
Pls. check the request below:

### Other details

https://restninja.io/share/b099118328a785e3d04884d4334a3338ee3b3d20/0

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Elite** [comment]
It was a client version issue :)

**Comment by LuanRT** [comment]
Your `params` are also wrong by the way.

**Comment by Elite** [comment]
Yes, figured that and I think that was the main reason. Thanks :)
