### ISSUE TITLE
Get a list of subscribed channels

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#63]
## Expected Behavior
Allow receiving a list of channels the user is subscribed to.

## Sample Code
`const channels = await youtube.getChannelList();`
```
{
  channels: [
    id: string,
    name: string,
    url: string
  ]
}

**Comment by walking-octopus** [comment]
`youtube.actions.browse("FEchannels")` can provide a list of subscribed channels. All that's left is a bit of parsing. Thanks for marking this as a good first issue, encouraging me to look into how the library I depend on works.

**Comment by walking-octopus** [comment]
I tried parsing the response. I'm not familiar with how the proper parser works, but here's my attempt.

```
let channels = await youtube.actions.browse("FEchannels");
channels = channels.data.contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.sectionListRenderer.contents[0].itemSectionRenderer.contents[0].shelfRenderer.content.expandedShelfContentsRenderer.items;
// console.log(channels);

channels.forEach(item => {
    console.log(`${item.channelRenderer.title.simpleText} (${item.channelRenderer.channelId})`);
});
```

**Comment by walking-octopus** [comment]
Also, it would require feed continuations.

**Comment by LuanRT** [comment]
> I tried parsing the response. I'm not familiar with how the proper parser works, but here's my attempt. It misses feed continuations but seems to work fine.
> 
> ```
> let channels = await youtube.actions.browse("FEchannels");
> channels = channels.data.contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.sectionListRenderer.contents[0].itemSectionRenderer.contents[0].shelfRenderer.content.expandedShelfContentsRenderer.items;
> // console.log(channels);
> 
> channels.forEach(item => {
>     console.log(`${item.channelRenderer.title.simpleText} (${item.channelRenderer.channelId})`);
> });
> ```

Nice! The new parser makes that much easier tho -- you can learn more about it here: #65. This feature will probably be implemented in the [`Library`](https://github.com/LuanRT/YouTube.js/blob/main/lib/parser/youtube/Library.js) class.

**Comment by walking-octopus** [comment]
I don't think this should be closed yet.

**Comment by walking-octopus** [comment]
Sorry for not getting around to this for so long. So many things to do lately.
