### ISSUE TITLE
Get a list of user's playlists

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#64]
## Current Behavior
I didn't find any way to receive a list of users' playlists, so I made a feature request.

## Sample Code
`await youtube.getSavedPlaylists();`
```
{
  playlists: [
    title: string,
    description: string,
    total_items: string,
    last_updated: string,
    views: string,
    id: string,
    thumbnail: object
  ]
}
```

**Comment by LuanRT** [comment]
This should now be available through the `youtube.account.getLibrary()` method. Any feedback would be appreciated.

**Comment by walking-octopus** [comment]
Thanks! It seems to work. I'll open an issue if anything goes wrong.
