### ISSUE TITLE
[9.3.0] ChipBarView/ChipView not found

### ISSUE THREAD

**Issue by iBicha** [LuanRT/YouTube.js#640]
### Steps to reproduce

1. Browse playlists (`FEplaylist_aggregation`) e.g. https://github.com/iBicha/yt2alt/pull/28/files#diff-4c2051f3371806711a8af031ea1c607d07a782cb4cf22e611b99cacb793429f5R140
2. Observe missing nodes errors

### Failure Logs

```shell
[YOUTUBEJS][Parser]: InnertubeError: ChipBarView not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
Introspected and JIT generated this class in the meantime:
class ChipBarView extends YTNode {
  static type = 'ChipBarView';

  chips: ObservedArray<YTNodes.ChipView> | null;

  constructor(data: RawNode) {
    super();
    this.chips = Parser.parse(data.chips, true, YTNodes.ChipView);
  }
}

[YOUTUBEJS][Parser]: InnertubeError: ChipView not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
Introspected and JIT generated this class in the meantime:
class ChipView extends YTNode {
  static type = 'ChipView';

  text: string;
  display_type: string;
  endpoint: NavigationEndpoint;
  chip_entity_key: string;

  constructor(data: RawNode) {
    super();
    this.text = data.text;
    this.display_type = data.displayType;
    this.endpoint = new NavigationEndpoint(data.tapCommand);
    this.chip_entity_key = data.chipEntityKey;
  }
}
```

### Expected behavior

No errors

### Current behavior

Errors

### Version

Default

### Anything else?

Relates to #639 - it's using that endpoint that I run into this

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
These look similar to the chip cloud renderers.

**Comment by Lcstyle** [comment]
Any chance you can merge this soon? Its blocking this tool: https://github.com/iBicha/yt2alt

**Comment by iBicha** [comment]
> Any chance you can merge this soon? Its blocking this tool: https://github.com/iBicha/yt2alt

Are you sure this is a blocker? Although the error is printed, you should be able to export all of your profile correctly.
Please let me know if this is not the case (or even create an issue on https://github.com/iBicha/yt2alt)

**Comment by Lcstyle** [comment]
> > Any chance you can merge this soon? Its blocking this tool: https://github.com/iBicha/yt2alt
> 
> Are you sure this is a blocker? Although the error is printed, you should be able to export all of your profile correctly. Please let me know if this is not the case (or even create an issue on https://github.com/iBicha/yt2alt)

https://github.com/iBicha/yt2alt/issues/32
