### ISSUE TITLE
[9.4.0] Channel header sometimes is not C4TabbedHeader

### ISSUE THREAD

**Issue by gifaldyazkaa** [LuanRT/YouTube.js#659]
### Steps to reproduce

I am currently building a REST API to see VTubers channel data from YouTube. I have the API running and having this issue.
Try to hit this endpoint: https://api.hoshiro.space/id/@amayaclorentine

On the first hit, you may receive the `banner`, `subscribers`, `videos`, and other objects that dynamically fetched from this library. Try to refreshing the page or re-send the request multiple times (for this purpose, it's okay to spam the API). Sometimes it returns the dynamic data (no error happening) and sometimes it won't (only returning static data from the database and throwing the error on the console).

---

Get a YouTube channel with `C4TabbedHeader` header (i'm following the example code using if statement to check the header).
Sometimes it gives you error and sometimes it works when re-fetching.

Here is my current code (adapted from the original Express code to improve readability):
```ts
// useYTData.ts
import { Innertube, YTNodes } from 'youtubei.js';

async () => {
    const client = await Innertube.create();
    const channel = await client.getChannel('UCRjLndN9OVEEQ9twOqwSnTg');

    if (channel.header?.is(YTNodes.C4TabbedHeader)) {
        const props = {
            picture: channel?.metadata.avatar,
            banner: channel?.header?.banner,
            subscribers: channel?.header?.subscribers?.text,
            videos: channel?.header?.videos_count?.text,
            is_verified: channel?.header?.author.is_verified,
            is_membership: !channel?.header?.sponsor_button?.is_disabled,
        };

        console.info(props);
    } else {
        throw new Error('Header is not C4TabbedHeader');
    }
};
```

### Failure Logs

```shell
27 |             console.info(props);
28 |         } else {
29 |             throw new Error('Header is not C4TabbedHeader');
                       ^
error: Header is not C4TabbedHeader
      at /home/azkaafx/projects/hoshiro/functions/useYTData.ts:29:19
```

### Expected behavior

Successfully getting a YouTube channel data without any errors.

### Current behavior

Getting a YouTube channel sometimes works, but sometimes (and mostly happen) it throw the `"Header is not C4TabbedHeader"` error.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
YouTube is slowly switching to using `PageHeader`s instead of `C4TabbedHeader`s, they've been A/B testing it since January and as time goes on will continue returning it more and more frequently until they eventually only return `PageHeader`s (that's how all of their A/B tests work).

If you look at the typescript types or auto-complete in your code editor, you'll notice that the channel header can be any of the following `C4TabbedHeader | CarouselHeader | InteractiveTabbedHeader | PageHeader`.

**Comment by gifaldyazkaa** [comment]
@absidue Thanks for your response and explanation! Now I'm able to get both data from `C4TabbedHeader` and `PageHeader` by adding extra else-if statement. So the current fixed code could be look like:

```ts
if (channel.header?.is(YTNodes.C4TabbedHeader)) {
    const props = {
        picture: channel?.metadata.avatar,
        banner: channel?.header?.banner,
        subscribers: channel?.header?.subscribers?.text,
        videos: channel?.header?.videos_count?.text,
        is_verified: channel?.header?.author.is_verified ? true : false,
        is_membership: channel?.header?.sponsor_button ? true : false,
        type: 'C4TabbedHeader',
    };

    res.status(200).send(props);
} else if (channel.header?.is(YTNodes.PageHeader)) {
    const props = {
        picture: channel?.metadata.avatar,
        banner: channel.header.content?.banner?.image,
        subscribers: channel?.header?.content?.metadata?.metadata_rows[1]?.metadata_parts[0].text?.text,
        videos: channel?.header?.content?.metadata?.metadata_rows[1].metadata_parts[1].text.text,
        is_verified: channel?.header?.content?.title?.text.runs[0].attachment ? true : false,
        is_membership: channel?.header.content?.actions?.actions_rows[0].actions[1] ? true : false,
        type: 'PageHeader',
    };

    res.status(200).send(props);
} else {
    throw new Error('Header is not one of the C4TabbedHeader or PageHeader');
}
```

So, it should be returning the data whether the header is `C4TabbedHeader` or `PageHeader`. And this works successfully on the API.

https://github.com/LuanRT/YouTube.js/assets/68645946/799093c7-18a1-4aac-a57c-42a5800d3f12
