### ISSUE TITLE
how to get typescript types?

### ISSUE THREAD

**Issue by gbarton** [LuanRT/YouTube.js#660]
### Question

I know I'm doing something wrong, but I cant figure it out!  I want to create a server in TS to download videos from yt, so I started messing with your excellent looking library.  When I hover over I'm getting typing which is awesome.

![image](https://github.com/LuanRT/YouTube.js/assets/1878953/5dabc3c6-7d6e-4291-b558-687a052d5439)

But if I want to declare the variable (say outside a try/catch) I cannot.

![image](https://github.com/LuanRT/YouTube.js/assets/1878953/c431c463-e0b6-444f-94d2-bb4f67afb057)

I cant find anywhere to pull the types into my .ts file, and doing the normal `npm install @types/youtubei.js` didnt work.

Any ideas?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
You can just import the type.

```ts
import { IStreamingData } from 'youtubei.js';

const streamingData: IStreamingData = { /** */ };
```

**Comment by gbarton** [comment]
ahh perfect, thank you so much!  Just cause I'm brain dead apparently, how do I get the Format type for the adaptive_formats as well?

**Comment by LuanRT** [comment]
> how do I get the Format type for the adaptive_formats as well?

That one should be inside `Misc`:
```ts
import { Misc } from 'youtubei.js';

const fmt: Misc.Format;
```

**Comment by gbarton** [comment]
You know what, I recreated the project and started again and now with enough trying TS eventually resolves things.  Thank you for an awesome library!

```
import { DownloadOptions } from "youtubei.js/dist/src/types";
import { VideoInfo } from "youtubei.js/dist/src/parser/youtube";
import { Format } from "youtubei.js/dist/src/parser/misc";
```

**Comment by YuriVivaldi** [comment]
How can I import VideoInfo class???
