### ISSUE TITLE
no update to video+audio for higher resolution?

### ISSUE THREAD

**Issue by ryznxx** [LuanRT/YouTube.js#665]
### High resolution and audio?
maybe i ask same question but im curious i already read docs
```javascript

const info = await yt.getBasicInfo('somevideoid');

const url = info.streaming_data?.formats[0].decipher(yt.session.player);
console.info('Playback url:', url);

// or:
const format = info.chooseFormat({ type: 'video+audio', quality: 'best' });
const url = format?.decipher(yt.session.player);
console.info('Playback url:', url);
```

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
YouTube doesn't provide any streams like that, you will have to download an audio stream and a video stream from the `adaptive_formats` array and then combine them with a tool like `ffmpeg`.

**Comment by ryznxx** [comment]
> YouTube doesn't provide any streams like that, you will have to download an audio stream and a video stream from the `adaptive_formats` array and then combine them with a tool like `ffmpeg`.

i dont think it works when run it on vercel

**Comment by gmagreti** [comment]
> > O YouTube não fornece nenhum fluxo desse tipo. Você terá que baixar um fluxo de áudio e um fluxo de vídeo do `adaptive_formats`array e então combiná-los com uma ferramenta como o `ffmpeg`.
> 
> não acho que funcione quando executado no vercel

Have you already tried doing this?
