### ISSUE TITLE
[1.4.3] [Youtube search filter for duration incorrect]

### ISSUE THREAD

**Issue by 404-Program-not-found** [LuanRT/YouTube.js#67]
## Expected Behavior

Youtube Search filters are not organized orthodoxically. This results in unexpected results for certain filter options.

## Current Behavior

What is the current behavior?
duration medium and long are switched - filtering medium results in videos of over 20 minutes while filtering long results in videos of 4-20 minutes.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. search for any query with `filters: { duration: "medium" }`
2. see the issue

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information

**Comment by LuanRT** [comment]
My bad😆 Thanks for reporting.

**Comment by 404-Program-not-found** [comment]
Haha, I was caught up by the same problem on my repo too
