### ISSUE TITLE
Allow passing poToken for unblock YouTube restrictions

### ISSUE THREAD

**Issue by unixfox** [LuanRT/YouTube.js#674]
### Describe your suggestion

Hello,
Could you please add the ability to pass the `poToken`? Here is a JSON example:
```
{
   "videoId":"aaaaaaa",
   "context":{
      "client":{
      },
   "serviceIntegrityDimensions": {
		"poToken": "verylongstring"
	}
}
```

Like it's already possible to do it with visitor_data.

This will allow to "unblock" the YouTube restrictions on a blocked IP where YouTube returns `Sign in to confirm you’re not a bot`.

Thank you

### Other details

https://github.com/iv-org/invidious/issues/4734

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by ppalone** [comment]
Hi @unixfox, will `poToken` work with Android clients or does it only work with Web embedded clients?

**Comment by kms0219kms** [comment]
Hi @unixfox and @LuanRT , is there any way to generate poToken without Selenium?
The @unixfox 's implement for generator is simply get poToken by Selenium, which might not be work on `youtubei.js/web`.

**Comment by unixfox** [comment]
It's not selenium but https://github.com/ultrafunkamsterdam/nodriver. won't work with selenium see https://github.com/iv-org/youtube-trusted-session-generator/issues/2

**Comment by kms0219kms** [comment]
> It's not selenium but [ultrafunkamsterdam/nodriver](https://github.com/ultrafunkamsterdam/nodriver). won't work with selenium see [iv-org/youtube-trusted-session-generator#2](https://github.com/iv-org/youtube-trusted-session-generator/issues/2)

Yeah, I just meant that it is *kind of* Selenium as it is automated browser driver. I want to get poToken without any browser drivers as it doesn't work on `youtubei.js/web`.

**Comment by retrouser955** [comment]
> generator

As far as I know, only full-on browsers are able to generate potoken.

**Comment by kms0219kms** [comment]
> > Yeah, I just meant that it is kind of Selenium as it is automated browser driver. I want to get poToken without any browser drivers as it doesn't work on youtubei.js/web.
> 
> As far as I know, only full-on browsers are able to generate potoken.

Yep, I am just curious that *HOW* youtube embed client generates poToken?
There is no sense for generating poToken by *magic* in *full-on* browsers.....

**Comment by kane50613** [comment]
How long will the token be able to live? Do I need to have a cron job to keep rotating it?

**Comment by kane50613** [comment]
It still says "Sign in to confirm you’re not a bot" after providing `visitor_data` and `po_token` generated on the machine with the same IP.

**Comment by mooleshacat** [comment]
> As far as I know, only full-on browsers are able to generate potoken.

YunzheZJU/youtube-po-token-generator

I am not sure if you have seen this repo, but apparently this person can obtain the visitor_data and then without opening a web browser they somehow calculate what the po-token is. The problem is it is in nodeJS I believe.

**Comment by kms0219kms** [comment]
> > As far as I know, only full-on browsers are able to generate potoken.
> 
> YunzheZJU/youtube-po-token-generator
> 
> I am not sure if you have seen this repo, but apparently this person can obtain the visitor_data with one request and then without opening a web browser or making another request they somehow calculate what the po-token is. The problem is it is in nodeJS I believe.
> 
> If this is true I _think_ it would cut back some of the traffic and speed things up on busy instances.

Yep, I have seen this repo and added this code to my service.

**Comment by retrouser955** [comment]
> > As far as I know, only full-on browsers are able to generate potoken.
> 
> YunzheZJU/youtube-po-token-generator
> 
> I am not sure if you have seen this repo, but apparently this person can obtain the visitor_data with one request and then without opening a web browser or making another request they somehow calculate what the po-token is. The problem is it is in nodeJS I believe.
> 
> If this is true I _think_ it would cut back some of the traffic and speed things up on busy instances.

Yes I think I know how youtube generates po tokens now. It is by using botguard. See, botguard gives you a challenge that only a "browser" (heavy quote on quotes) can solve and if you successfully solve this, they will return a trusted token to you. You can find a deeper analysis on https://github.com/LuanRT/BgUtils

**Comment by mooleshacat** [comment]
> It is by using botguard.

Correct I've heard others talking about BotGuard and DroidGuard. The only question is, can this be implemented directly into invidious, or into one of the po-token generators?

I've been trying myself to make the code work, because the other code seems to be "dirty" to me because it opens a web browser to get the tokens, which costs ram, speed, and bandwidth. My problem is I have no idea what I am doing, and this is in a language I do not understand even on a basic level (nodejs)

Are there any repos that use this method that can be implemented while we wait for Invidious to provide their solution?

**Comment by retrouser955** [comment]
The repo I have provided allows you with is to the codebase for a package that allows you to get the PoToken without the use of a browser. Check it's examples for more info.

**Comment by SajjadSarwarPK** [comment]
Can someone please help me to understand, I have passed the po token and visitor data. it asks me to authenticate and then it started returning the video download urls on a flask service. But problem is that those urls can only be downloaded on that cloud machine not on local machine. Can someon please guide to get red of that in case of PO_Token is being used?
