### ISSUE TITLE
1.4.3 getContinuation is not being recognized in typescript from search results

### ISSUE THREAD

**Issue by Coinhexa** [LuanRT/YouTube.js#68]
## Expected Behavior

Search response type should have getContinuation method

## Current Behavior

<img width="1325" alt="Screenshot 2022-06-06 at 11 25 24 AM" src="https://user-images.githubusercontent.com/70217835/172103429-8202a52a-d3dd-4d49-b811-93409ebd7faf.png">

### Steps to Reproduce

Just do a search in any typescript file and try to access getContinuation

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information

**Comment by Coinhexa** [comment]
The release is still not fixed

**Comment by LuanRT** [comment]
> The release is still not fixed

Sorry about that — I labeled this as fixed because, technically, this has already been fixed; but only in the dev version. See #65.
