### ISSUE TITLE
<10.1.0> <LOGIN_REQUIRED>

### ISSUE THREAD

**Issue by nikunjgupta586** [LuanRT/YouTube.js#696]
### Steps to reproduce

use getbasicinfo() for any of the youtube video with any of the server location.
result throws "LOGIN_REQUIRED" for any of the youtube videos.
we can't access any youtube video without login

### Failure Logs

```shell
status: "LOGIN_REQUIRED"
```

### Expected behavior

need it to be worked without account login

### Current behavior

throwing "LOGIN_REQUIRED" for any of the youtube videos

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hi! Can you provide the full error message?

**Comment by retrouser955** [comment]
I'm not entirely sure but [this](https://www.reddit.com/r/LocalLLaMA/comments/1dd8c62/google_is_testing_a_ban_on_watching_videos/) could be related.

**Comment by nikunjgupta586** [comment]
@LuanRT below is the response we are getting from getbasicinfo() function for any of the youtube video.

info --  VideoInfo {
  streaming_data: undefined,
  playability_status: {
    status: 'LOGIN_REQUIRED',
    reason: 'Sign in to confirm you’re not a bot',
    embeddable: false,
    audio_only_playablility: null,
    error_screen: PlayerErrorMessage {
      type: 'PlayerErrorMessage',
      subreason: [Text],
      reason: [Text],
      proceed_button: [Button],
      thumbnails: [Array],
      icon_type: 'ERROR_OUTLINE'
    }
  },
  player_config: undefined,
  basic_info: {
    embed: null,
    channel: null,
    is_unlisted: undefined,
    is_family_safe: undefined,
    category: null,
    has_ypc_metadata: null,
    start_timestamp: null,
    end_timestamp: null,
    view_count: undefined,
    like_count: undefined,
    is_liked: undefined,
    is_disliked: undefined
  },
  annotations: undefined,
  storyboards: undefined,
  endscreen: undefined,
  captions: undefined,
  cards: undefined
}

**Comment by retrouser955** [comment]
@LuanRT as I suspected, it is definitely because of the A/B testing YouTube is doing to prevent scrappers. They secured it on their server-side so even YouTube's clients are affected.

**Comment by honzawashere** [comment]
I bet this is just that page that pops up usually on servers or suspicious clients saying "Please sign in to verify you are not a bot" or something like that. just use auth as shown in examples of this repository and you should be good

**Comment by unixfox** [comment]
Related: https://github.com/LuanRT/YouTube.js/issues/674
