### ISSUE TITLE
Manifest generated with .toDash results in only playing sound in dash.js

### ISSUE THREAD

**Issue by Reilaen** [LuanRT/YouTube.js#710]
### Question

Hi everyone,

i am not sure if it is a bug or if i am just doing something wrong.

Basically i copied the streaming example from this git (https://github.com/LuanRT/YouTube.js?tab=readme-ov-file#streaming) and only got the sound played back.

Upon using the debug parameters of dash.js i got told that there is no video found in the manifest.
But when i manually check the links in the manifest there are audio and video urls in it.

So i uploaded an exported mpd into the dash.js reference player on the dash.js website to see if it is a problem with my implementation and got the result that it plays the video without problems.

Any ideas or hints how to solve this are appreciated. If further information is needed i am also happy to provide that.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
Does turning on logging in dash.js provide a hint as to what is going on?
https://dashif.org/dash.js/pages/advanced/logging.html

**Comment by Reilaen** [comment]
I kind found out what the problem is, even though i don't really know why it happens.
The current stable dash.js (4.7.4) seems to be unable to handle the manifest file that gets generated, while the latest nightly build (5.0.0) can.
