### ISSUE TITLE
v10.3.0 - ClientSideToggleMenuItem not found

### ISSUE THREAD

**Issue by mrd83** [LuanRT/YouTube.js#727]
### Steps to reproduce

NOTE: the issue is directly caused by @Andrews54757 's [FastStream extension](https://github.com/Andrews54757/FastStream/) - but since it uses all of the classes from YouTube.js I sincerely hope this report is actually valid. Normally I'd create a PR instead - but since I don't use YouTube.js >directly< - I'm unable to test the code.

1. Start yt video with debugging console opened
2. Wait for the message to appear.

### Failure Logs

```shell
[YOUTUBEJS][Parser]: Error: ClientSideToggleMenuItem not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
Introspected and JIT generated this class in the meantime:
(...)
```

### Expected behavior

No such error

### Current behavior

Here's auto-generated class:
```
class ClientSideToggleMenuItem extends YTNode {
  static type = 'ClientSideToggleMenuItem';
  default_text: Text;
  default_icon: {
    icon_type: string
  };
  toggled_text: Text;
  toggled_icon: {
    icon_type: string
  };
  menu_item_identifier: string;
  command: {
    click_tracking_params: string,
    toggle_live_chat_timestamps_endpoint: NavigationEndpoint
  };
  constructor(data: RawNode) {
    super();
    this.default_text = new Text(data.defaultText);
    this.default_icon = {
      icon_type: data.defaultIcon.iconType
    };
    this.toggled_text = new Text(data.toggledText);
    this.toggled_icon = {
      icon_type: data.toggledIcon.iconType
    };
    this.menu_item_identifier = data.menuItemIdentifier;
    this.command = {
      click_tracking_params: data.command.clickTrackingParams,
      toggle_live_chat_timestamps_endpoint: new NavigationEndpoint(data.command.toggleLiveChatTimestampsEndpoint)
    };
  }
}
```
Proof:
![issue 1 - ClientSideToggleMenuItem](https://github.com/user-attachments/assets/99121293-cb67-4839-bf1e-f51ba0a44cff)

### Version

Default

### Anything else?

There's another: "ShortsLockupView". Should I also report it?
![issue 2a - ShortsLockupView](https://github.com/user-attachments/assets/5b95b87e-4e64-4083-a42a-b0d979015b77)

### Checklist

- [ ] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by iBicha** [comment]
https://github.com/LuanRT/YouTube.js/issues/595
