### ISSUE TITLE
Dash Stream ends abruptly after a variable amount of seconds.

### ISSUE THREAD

**Issue by Reilaen** [LuanRT/YouTube.js#728]
### Question

I am generating a dash manifest and change the urls that it uses to my proxy and send the generated manifest via websockets to my clients. These clients then load the manifest in a default dash.js player. 

In the beginning the requests work flawlessly, but after a variable amount of seconds, requests begin to fail with the upstream server sending 403 errors.

I am not sure if maybe i miss some header/parameter manipulation or my configuration is wrong or there is a po_token issue, that seems to currently create some trouble for others and i am really out of ideas, what i could try to fix this issue.

I tried it with visitor_data and po_token and without, but got the same result.

I appreciate any kind of idea or help to solve this, if there are any questions i am happy to answer them.
Below i will also provide the basic setup i use currently.

The code for the manifest manipulation looks like this:
```
const youtube = await Innertube.create()
const videoInfo = await youtube.getInfo('EuOP_HGTN4Y')

const manifest = await videoInfo.toDash((destinationUrl) => {
	destinationUrl.searchParams.append('_host', destinationUrl.host)
	destinationUrl.protocol = 'https'
	destinationUrl.host = 'localhost'
	destinationUrl.port = '8080'

	return destinationUrl
})
```

For the actual proxying i use an openresty server with this configuration:
```
server {
        listen 8080 ssl;
        http2 on;
        server_name localhost;

        ssl_protocols TLSv1.3;
        ssl_early_data on;
        ssl_certificate C:/certificates/localhost.pem;
        ssl_certificate_key C:/certificates/localhost-key.pem;
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout 5m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        proxy_http_version 1.1;

        resolver 1.1.1.1 1.0.0.1 valid=300s;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' '*' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization, x-goog-visitor-id, x-origin, x-youtube-client-version, x-youtube-client-name, x-goog-api-format-version, x-user-agent, Accept-Language, Range, Referer' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
        add_header 'Access-Control-Allow-Credentials' true always;

        location / {     
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Max-Age' 86400;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            if ($arg__host = "") {
                return 400 "Invalid query.";
            }

            set $_host $arg__host;

            rewrite_by_lua_block {
                local uri_arguments, err = ngx.req.get_uri_args()
                
                uri_arguments['_host'] = nil
                
                ngx.req.set_uri_args(uri_arguments)
            }

            proxy_pass https://$_host;
            proxy_intercept_errors on;
            error_page 301 302 307 = @handle_redirects;
        }

        location @handle_redirects {
            set $upstream_origin $upstream_http_location;
            proxy_pass $upstream_origin;
        }
    }
```

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by rizer234** [comment]
what did you do to resolve this issue?
i have this problem too...

**Comment by clytras** [comment]
@Reilaen can you please share a potential solution to this problem?
I'm facing the same issue as well, having the video playing only for 59 seconds and then it stops due to 403 errors when trying to fetch next chunks of data.

**Comment by Reilaen** [comment]
@rizer234 @clytras

You need to provide po_token and visitor_data in the InnertubeConfig.
```
const innertube = await Innertube.create({
    "po_token": "",
    "visitor_data": ""
})
```

To generate those you can use: https://github.com/iv-org/youtube-trusted-session-generator
According to what i read you need to refresh them every 1-2 weeks.

**Comment by clytras** [comment]
Thank you @Reilaen.
Luan has shared a repo that has some utilities to extract those tokens inside the browser or using a JS runtime, you can find it here https://github.com/LuanRT/BgUtils.
