### ISSUE TITLE
bleeding-edge YouTube search results aren't parsed

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#73]
## Current Behavior
It just returns unparsed data. I know you're likely already working on it, but I thought making this issue would help to monitor progress.

### Steps to Reproduce
```
const json = await await youtube.search("Hello, world!");
for (const video of json.payload.videos) {
  print(video.title);
  resultsModel.append({
    videoTitle: video.title,
    channel: video.channel,
    thumbnail: video.metadata.thumbnails[0].url,
    published: video.metadata.published,
    views: video.metadata.view_count,
    duration: video.metadata.duration,
    id: video.id,
  });
}
```

### Failure
`results.videos` not found.

## Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information

**Comment by Wykerd** [comment]
This should be fixed in v2 with the new parsers. See #65 and #44
