### ISSUE TITLE
v10.3.0 SyntaxError: Unexpected identifier 'assert'

### ISSUE THREAD

**Issue by thicccat688** [LuanRT/YouTube.js#734]
### Steps to reproduce

Running this code on Node v22.3.0 produces the error:

```
import { channelId } from '@gonetone/get-youtube-id-by-url';
import { Innertube } from 'youtubei.js/web';

const ytChannelId = await channelId(channelData.url);

const scraper = await Innertube.create({
    fetch: async (input: RequestInfo | URL, init?: RequestInit) => {
      return fetch(input, init);
    },
  });

await scraper.getChannel(ytChannelId);
```

### Failure Logs

```shell
import package_json from '../../package.json' assert { type: 'json' };
                                              ^^^^^^

SyntaxError: Unexpected identifier 'assert'
```

### Expected behavior

The package runs without giving an error for the deprecated assert identifier.

### Current behavior

The package breaks because Node's latest versions no longer support the `assert` statement.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
You are trying to import the web version in node.js, please change your import from `youtubei.js/web` to `youtubei.js`..
