### ISSUE TITLE
Youtubei only get list of comment thread but doesn't get replies 

### ISSUE THREAD

**Issue by TechBroCode** [LuanRT/YouTube.js#738]
The YouTubei is working very well. Kudos to the developers of this library. Although, my problem is that i'm able to get comment threads but unable to get replies to each comments.

**Comment by absidue** [comment]
So are you saying that the `CommentThread#getReplies()` method isn't working?

**Comment by TechBroCode** [comment]
It's now working brother, I made a mistake.
