### ISSUE TITLE
Access to rr4---sn-ja5gvjv-hqxz.googlevideo.com was denied

### ISSUE THREAD

**Issue by rogerpadilla** [LuanRT/YouTube.js#740]
### Question

Hello, I am trying to obtain the URL to download a video, but when I open the URL the browser shows me the message below saying I am unauthorized to view this page (HTTP error code 403).

This is my current code:
```ts
async function download(id: string, youtubei: InnerTube) {
  return youtubei
    .getStreamingData(id, {
      type: 'audio',
      quality: 'best',
      format: 'mp4',
    })
    .then((res) => {
      console.log('** download res', res);
      return res.url;
    });
}

const { poToken, visitorData } = await scrapeYouTubeSession('RPa3_AD1_Vs');

 const youtubei = await Innertube.create({
    po_token: poToken,
    visitor_data: visitorData,
    // generate_session_locally: true,
    // cache: new UniversalCache(false),
});

await download('RPa3_AD1_Vs', youtubei);
```

And it returns an URL, but when I try to open the URL, i get the following error:
```
Access to rr4---sn-ja5gvjv-hqxz.googlevideo.com was denied.

You don't have authorization to view this page.

HTTP ERROR 403
```

Please help.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
https://github.com/LuanRT/YouTube.js/issues/594#issuecomment-1935138060

**Comment by rogerpadilla** [comment]
Solved [here](https://github.com/LuanRT/YouTube.js/issues/594#issuecomment-2315138916). Thanks again for all the help 🙏🏽

**Comment by twicer-is-coder** [comment]
Po Token solves sign in and blocked IP issue?  scrapeYouTubeSession('RPa3_AD1_Vs') is this custom implementation or do you know how to get the poToken?

**Comment by retrouser955** [comment]
@twicer-is-coder you can use [this](https://github.com/LuanRT/bgutils)
