### ISSUE TITLE
10.4.0: `SearchFilters` no longer accessible as a named export

### ISSUE THREAD

**Issue by kellenmace** [LuanRT/YouTube.js#750]
### Steps to reproduce

In previous versions of YouTube.js, I was able to access `SearchFilters` as a named export and use it in my TypeScript app like this:
```ts
import { Innertube, type SearchFilters } from 'youtubei.js';

const youtube = await Innertube.create({
    lang: 'en',
    location: 'US',
});

const filters: SearchFilters = {
    type: 'video',
    // Conditionally add other filters here.
};

const response = await youtube.search("tech news", filters);
```

In the current version, it is no longer available as a named export though. Is there a way to access `SearchFilters` that I'm unaware of, or does it need to be exposed once again for library consumers to use?

### Failure Logs

```shell
Module '"youtubei.js"' has no exported member 'SearchFilters'.
```

### Expected behavior

I expected to be able to access the type of `SearchFilters` in my TypeScript app.

### Current behavior

The type of `SearchFilters` is not accessible in my TypeScript app.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by hextor1** [comment]
@kellenmace  Hello When New version is released?

**Comment by kellenmace** [comment]
> @kellenmace Hello When New version is released via NPM?

* In version 9.4.0, `SearchFilters` was available as a named export in the `src/Innertube.ts` file.
* As of version 10.0.0, that export has been moved to `src/types/Misc.ts` so now consumers of the YouTube.js library can no longer access it.

**Comment by LuanRT** [comment]
@kellenmace It is still accessible:
```ts
import { Types } from 'youtubei.js';

const filters: Types.SearchFilters = {
  duration: 'all',
  features: ['hd'],
  sort_by: 'view_count',
  upload_date: 'all'
}
```

**Comment by kellenmace** [comment]
Ah! Got it. Thanks so much, @LuanRT 👍
