### ISSUE TITLE
10.5.0: InnertubeError: Something went wrong at ShortsLockupView!

### ISSUE THREAD

**Issue by elektracodes** [LuanRT/YouTube.js#771]
### Steps to reproduce

The issue still persists.

This is the id of MrBeast video for example `tnTPaLOaHz8`

My code is like this

```
  const requestedItemId = 'tnTPaLOaHz8'
  const video = await yt.getInfo(requestedItemId);
```

### Failure Logs

```shell
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ShortsLockupView!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (/path/to/node_modules/youtubei.js/bundle/node.cjs:14521:32)
    at parseItem (/path/to/node_modules/youtubei.js/bundle/node.cjs:14885:7)
    at Object.parseArray (/path/to/node_modules/youtubei.js/bundle/node.cjs:14901:22)
    at new ReelShelf (/path/to/node_modules/youtubei.js/bundle/node.cjs:7069:33)
    at parseItem (/path/to/node_modules/youtubei.js/bundle/node.cjs:14881:22)
    at Object.parseArray (/path/to/node_modules/youtubei.js/bundle/node.cjs:14901:22)
    at new StructuredDescriptionContent (/path/to/node_modules/youtubei.js/bundle/node.cjs:7101:33)
    at Object.parseItem (/path/to/node_modules/youtubei.js/bundle/node.cjs:14881:22)
    at new EngagementPanelSectionList (/path/to/node_modules/youtubei.js/bundle/node.cjs:7124:35)
    at parseItem (/path/to/node_modules/youtubei.js/bundle/node.cjs:14881:22) {
  info: {
    stack: "TypeError: Cannot destructure property 'content' of 'data' as it is undefined.\n" +
      '    at Function.fromAttributed (/path/to/node_modules/youtubei.js/bundle/node.cjs:5534:13)\n' +
      '    at new ShortsLockupView (/path/to/node_modules/youtubei.js/bundle/node.cjs:12576:26)\n' +
      '    at parseItem (/path/to/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at Object.parseArray (/path/to/node_modules/youtubei.js/bundle/node.cjs:14901:22)\n' +
      '    at new ReelShelf (/path/to/node_modules/youtubei.js/bundle/node.cjs:7069:33)\n' +
      '    at parseItem (/path/to/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at Object.parseArray (/path/to/node_modules/youtubei.js/bundle/node.cjs:14901:22)\n' +
      '    at new StructuredDescriptionContent (/path/to/node_modules/youtubei.js/bundle/node.cjs:7101:33)\n' +
      '    at Object.parseItem (/path/to/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at new EngagementPanelSectionList (/path/to/node_modules/youtubei.js/bundle/node.cjs:7124:35)',
    classdata: '{\n' +
      '  "entityId": "shorts-shelf-item-LbcXI5vrt0I",\n' +
      '  "accessibilityText": "Mr Beast playing Forklift |  rolling over #mrbeast #roblox #shorts #compilation, 10K views - play Short",\n' +
      '  "thumbnail": {\n' +
      '    "sources": [\n' +
      '      {\n' +
      '        "url": "https://i.ytimg.com/vi/LbcXI5vrt0I/oardefault.jpg?sqp=-oaymwEdCJUDENAFSFWQAgHyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLAiVqUxJBF5pmCxPtizdxWLH7XSKQ",\n' +
      '        "width": 405,\n' +
      '        "height": 720\n' +
      '      }\n' +
      '    ]\n' +
      '  },\n' +
      '  "onTap": {\n' +
      '    "innertubeCommand": {\n' +
      '      "clickTrackingParams": "CCIQh_YEGBwiEwjilfCpo-uIAxX7w0kHHY_IGxGaAQUIRRD4HQ==",\n' +
      '      "commandMetadata": {\n' +
      '        "webCommandMetadata": {\n' +
      '          "url": "/shorts/LbcXI5vrt0I",\n' +
      '          "webPageType": "WEB_PAGE_TYPE_SHORTS",\n' +
      '          "rootVe": 37414\n' +
      '        }\n' +
      '      },\n' +
      '      "reelWatchEndpoint": {\n' +
      '        "videoId": "LbcXI5vrt0I",\n' +
      '        "playerParams": "8AEByANFuAQfogYVAa6PwSZ7LENqkuxVLcZQNjMz8aAlkAcC",\n' +
      '        "thumbnail": {\n' +
      '          "thumbnails": [\n' +
      '            {\n' +
      '              "url": "https://i.ytimg.com/vi/LbcXI5vrt0I/frame0.jpg",\n' +
      '              "width": 720,\n' +
      '              "height": 1280\n' +
      '            }\n' +
      '          ],\n' +
      '          "isOriginalAspectRatio": true\n' +
      '        },\n' +
      '        "overlay": {\n' +
      '          "reelPlayerOverlayRenderer": {\n' +
      '            "style": "REEL_PLAYER_OVERLAY_STYLE_SHORTS",\n' +
      '            "trackingParams": "CCMQsLUEIhMI4pXwqaPriAMV-8NJBx2PyBsR",\n' +
      '            "reelPlayerNavigationModel": "REEL_PLAYER_NAVIGATION_MODEL_UNSPECIFIED"\n' +
      '          }\n' +
      '        },\n' +
      '        "params": "CB8wAg%3D%3D",\n' +
      '        "sequenceProvider": "REEL_WATCH_SEQUENCE_PROVIDER_RPC",\n' +
      '        "sequenceParams": "KsYDCg0KCzVPRlBDZ1M1RkxjCg0KCzNlZV8yVGRJUlF3Cg0KCzBqVkpuNnl6VVJJCg0KC0hVWUNWai1GZ3pBCg0KC1BuaUVKaG9SSVhZCg0KC0VxYWFGa3NHVW4wCg0KCy1Bd296VU5KdUZBCg0KC2txdzRuOTk1M2l3Cg0KC0VQaUVTc05Ld2FvCg0KC3g2OWgyNXFVeXNNCg0KC2dkb3hyUThGRTlvCg0KC3VfV1FXMF9lWmZrCg0KC0RuV1BERHBpaUVNCg0KC0hDQ0lQTUxjWlpZCg0KC05EMk5XQWhsUUtvCg0KC3BwUnFEa2Nva0pZCg0KC0hhX3FMWXRhWmpNCg0KC3BsX3FkUE5PNDdVCg0KC0NxaW9SbDZFX09vCg0KC1h3TDM1TU4zcG5BCg0KC1hvaWVkNVd6Y1VRCg0KC0hKcXNyWjdwMWg0Cg0KC25YOXhfS2NQZmljCg0KC0ZUakFVZU9vaUFjCg0KC2xYUHI2X1Q4SXk0Cg0KC3ZCN29tODQwNi1FCg0KCzdORmJNUVZhQU84Cg0KC1hITVFHcm9YVUhVCg0KC0xiY1hJNXZydDBJCg0KCzlxSktwR2RoZUg4EBwYH1AZaAGKAREaDwoNCgt0blRQYUxPYUh6OJABBQ%3D%3D",\n' +
      '        "loggingContext": {\n' +
      '          "vssLoggingContext": {\n' +
      '            "serializedContextData": "CgIIDA%3D%3D"\n' +
      '          },\n' +
      '          "qoeLoggingContext": {\n' +
      '            "serializedContextData": "CgIIDA%3D%3D"\n' +
      '          }\n' +
      '        },\n' +
      '        "ustreamerConfig": "CAwSGG1MdndaZU9qYzlpR3pxNnFMMkxGS1Q0PQ=="\n' +
      '      }\n' +
      '    }\n' +
      '  },\n' +
      '  "indexInCollection": 28,\n' +
      '  "overlayMetadata": {\n' +
      '    "secondaryText": {\n' +
      '      "content": "10K views"\n' +
      '    }\n' +
      '  },\n' +
      '  "loggingDirectives": {\n' +
      '    "trackingParams": "CCIQh_YEGBwiEwjilfCpo-uIAxX7w0kHHY_IGxE=",\n' +
      '    "visibility": {\n' +
      '      "types": "12"\n' +
      '    },\n' +
      '    "enableDisplayloggerExperiment": true\n' +
      '  }\n' +
      '}'
  },
  date: 2024-09-30T18:16:49.036Z,
  version: '10.5.0'
}
```

### Expected behavior

Being able to parse the video

### Current behavior

Fails to parse any video

### Version

Default

### Anything else?

I know in the previous released you said that this was playing, but most of my videos fail right now

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by hextor1** [comment]
I am also facing this same error @elektracodes

**Comment by hextor1** [comment]
[YOUTUBEJS][Parser]: w3 [Error]: Something went wrong at ShortsLockupView!
 This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
     at _J (/home/developer/mp3juice.land/.next/server/chunks/117.js:17:14081)
     at _X (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7733)
     at _0 (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7877)
     at new a8 (/home/developer/mp3juice.land/.next/server/chunks/117.js:4:89963)
     at _X (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7613)
     at _0 (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7877)
     at new ri (/home/developer/mp3juice.land/.next/server/chunks/117.js:4:90454)
     at _X (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7613)
     at new rs (/home/developer/mp3juice.land/.next/server/chunks/117.js:4:90632)
     at _X (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7613) {
   info: {
     stack: "TypeError: Cannot destructure property 'content' of 'e' as it is undefined.\n" +
       '    at sk.fromAttributed (/home/developer/mp3juice.land/.next/server/chunks/117.js:4:63034)\n' +
       '    at new gN (/home/developer/mp3juice.land/.next/server/chunks/117.js:4:193043)\n' +
       '    at _X (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7613)\n' +
       '    at _0 (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7877)\n' +
       '    at new a8 (/home/developer/mp3juice.land/.next/server/chunks/117.js:4:89963)\n' +
       '    at _X (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7613)\n' +
       '    at _0 (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7877)\n' +
       '    at new ri (/home/developer/mp3juice.land/.next/server/chunks/117.js:4:90454)\n' +
       '    at _X (/home/developer/mp3juice.land/.next/server/chunks/117.js:26:7613)\n' +
       '    at new rs (/home/developer/mp3juice.land/.next/server/chunks/117.js:4:90632)',
     classdata: '{\n' +
       '  "entityId": "shorts-shelf-item-tBcFHeLJy3Q",\n' +
       '  "accessibilityText": "Bagaimana kita mendapatkan hidup kekal? #putuayubnakbali #renunganayatalkitab #renungankristen, 1.1K views - play Short",\n' +
       '  "thumbnail": {\n' +
       '    "sources": [\n' +
       '      {\n' +
       '        "url": "https://i.ytimg.com/vi/tBcFHeLJy3Q/oardefault.jpg?sqp=-oaymwEdCJUDENAFSFWQAgHyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLA7bR8Pr8WDpl-FXX2T5S4nkarAyw",\n' +
       '        "width": 405,\n' +
       '        "height": 720\n' +
       '      }\n' +
       '    ]\n' +
       '  },\n' +
       '  "onTap": {\n' +
       '    "innertubeCommand": {\n' +
       '      "clickTrackingParams": "CC8Qh_YEGB0iEwj9j7n4w-yIAxWpyk8IHaCuA26aAQUIRRD4HQ==",\n' +
       '      "commandMetadata": {\n' +
       '        "webCommandMetadata": {\n' +
       '          "url": "/shorts/tBcFHeLJy3Q",\n' +
       '          "webPageType": "WEB_PAGE_TYPE_SHORTS",\n' +
       '          "rootVe": 37414\n' +
       '        }\n' +
       '      },\n' +
       '      "reelWatchEndpoint": {\n' +
       '        "videoId": "tBcFHeLJy3Q",\n' +
       '        "playerParams": "8AEByANFuAQfogYVAa6PwSYgj8dSUmBpNnFagsr3TWtWkAcC",\n' +
       '        "thumbnail": {\n' +
       '          "thumbnails": [\n' +
       '            {\n' +
       '              "url": "https://i.ytimg.com/vi/tBcFHeLJy3Q/frame0.jpg",\n' +
       '              "width": 720,\n' +
       '              "height": 1280\n' +
       '            }\n' +
       '          ],\n' +
       '          "isOriginalAspectRatio": true\n' +
       '        },\n' +
       '        "overlay": {\n' +
       '          "reelPlayerOverlayRenderer": {\n' +
       '            "style": "REEL_PLAYER_OVERLAY_STYLE_SHORTS",\n' +
       '            "trackingParams": "CDAQsLUEIhMI_Y-5-MPsiAMVqcpPCB2grgNu",\n' +
       '            "reelPlayerNavigationModel": "REEL_PLAYER_NAVIGATION_MODEL_UNSPECIFIED"\n' +
       '          }\n' +
       '        },\n' +
       '        "params": "CB8wAg%3D%3D",\n' +
       '        "sequenceProvider": "REEL_WATCH_SEQUENCE_PROVIDER_RPC",\n' +
       '        "sequenceParams": "KsYDCg0KC3prRmx5Q2I2WTc4Cg0KC25FYm4tbzlEc0FnCg0KCzBlZWZRMjFOdl8wCg0KC3BsTXdPd0N3Z2tZCg0KC3B0NFdUSjJFQUZ3Cg0KC0ktUVNVZUdSby1vCg0KC24zRFRQMkg0a1U0Cg0KC3lDclZ0ZlNOQzVBCg0KC0J6VlgyWnlQUWFBCg0KC2w4NDY4eFRWdUhrCg0KC1lWMFhFYWNtZEE0Cg0KC04wWmhGTFc3TWc0Cg0KC2xtcTJZRnFhNkhrCg0KCzJaek0zMzhBeGQ0Cg0KC1lfZVMxNlF2OWcwCg0KC1lVVFBmSE0wXzdvCg0KC2JVaElaLTR2bWVRCg0KC3IydTVBb0VQdzUwCg0KC0FWUFpEelJmSWN3Cg0KC21nc1M1T3dhcDEwCg0KC2x4UXBrYS1ScDVjCg0KCy1UbTRWV2VWeXhFCg0KC2E3T0hIc0tLUUJ3Cg0KC1ZLZHk5NWg0X1YwCg0KC1pCRHZPdjhNeE1RCg0KC1E3SzVjbV9FT0ljCg0KC29Vd1l0SThQWVR3Cg0KC2FVVGJHWEo4OTNJCg0KC1h3bS1ERV9OeEJVCg0KC3RCY0ZIZUxKeTNREB0YH1AZaAGKAREaDwoNCgt4WWxOZUhTM1R1d5ABBQ%3D%3D",\n' +
       '        "loggingContext": {\n' +
       '          "vssLoggingContext": {\n' +
       '            "serializedContextData": "CgIIDA%3D%3D"\n' +
       '          },\n' +
       '          "qoeLoggingContext": {\n' +
       '            "serializedContextData": "CgIIDA%3D%3D"\n' +
       '          }\n' +
       '        },\n' +
       '        "ustreamerConfig": "CAwSGG1MdndaZU9qYzlpR3pxNnFMMkxGS1Q0PQ=="\n' +
       '      }\n' +
       '    }\n' +
       '  },\n' +
       '  "indexInCollection": 29,\n' +
       '  "overlayMetadata": {\n' +
       '    "secondaryText": {\n' +
       '      "content": "1.1K views"\n' +
       '    }\n' +
       '  },\n' +
       '  "loggingDirectives": {\n' +
       '    "trackingParams": "CC8Qh_YEGB0iEwj9j7n4w-yIAxWpyk8IHaCuA24=",\n' +
       '    "visibility": {\n' +
       '      "types": "12"\n' +
       '    },\n' +
       '    "enableDisplayloggerExperiment": true\n' +
       '  }\n' +
       '}'
   },
   date: 2024-10-01T06:15:22.289Z,
   version: '10.5.0'
 }
