### ISSUE TITLE
10.5.0 - Getting a 400 whenever trying to get account settings suddenly with multiple accounts. They all used to work a few days ago

### ISSUE THREAD

**Issue by MrGrasss** [LuanRT/YouTube.js#783]
### Steps to reproduce

const yt = await Innertube.create()
 
yt.session.on("auth", async (data: any) => {
        const message = "Successfully signed in!";
        yt.session.logged_in = true;
        console.log(message);

        let accInfo: AccountInfo;
        let settings: Settings;
        let channel_id = null;
        let restricted = false;
        let ipBanned = false;

        try {
            accInfo = await yt.account.getInfo();
            settings = await yt.account.getSettings();

            const args = {
                browseId: "SPaccount_advanced",
                parse: true as const
            };

            const response = await yt.actions.execute('/browse', args);

            channel_id = [...response.contents_memo.get('ItemSection')]
                .flatMap(item => item["contents"])
                .find(option => option.type === 'SettingsOptions' && option.title.text === 'Channel ID')?.options[0]?.short_url;

        } catch (error) {
            // Account is restricted on 403
            if (error.code === 403) {
                console.error("Account Restricted:", error.code || error.message || error);
                restricted = true;
            } else {
                console.error("Account might have banned this ip or shadowbanned:", error.code || error.message || error);
                ipBanned = true;
            }
        }

await yt.session.signIn(auth_key);

### Failure Logs

```shell
https://www.youtube.com/youtubei/v1/account/accounts_list?prettyPrint=false&alt=json failed with status 400
```

### Expected behavior

Getting the account settings with a appropriate error message

### Current behavior

Getting 400 when trying to get the account settings

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by PurrsonalPawtrait** [comment]
I am getting the same error, been trying to fix it for a while nothing seems to work.

**Comment by MrGrasss** [comment]
The recent commit has fixed this issue but I think it still persists on VideoUpload..

@LuanRT

**Comment by unixfox** [comment]
More details:
```
  version: "11.0.1",
  info: "{\n" +
    '  "error": {\n' +
    '    "code": 400,\n' +
    '    "message": "Request contains an invalid argument.",\n' +
    '    "errors": [\n' +
    "      {\n" +
    '        "message": "Request contains an invalid argument.",\n' +
    '        "domain": "global",\n' +
    '        "reason": "badRequest"\n' +
    "      }\n" +
    "    ],\n" +
    '    "status": "INVALID_ARGUMENT"\n' +
    "  }\n" +
    "}\n"
}
```

**Comment by MrGrasss** [comment]
Just update to latest commit should be fixed
