### ISSUE TITLE
How to get "Courses" from "Explore".

### ISSUE THREAD

**Issue by ybd-project-ver1** [LuanRT/YouTube.js#797]
### Question

How do I get "Courses" content from YouTube "Explore"?
Currently YouTube.js has a `getTrending` function, but no `getCourses` function.
Thank you in advance.

![image](https://github.com/user-attachments/assets/bb1e1f5f-8b58-4b38-a09c-46c451824520)

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
For future reference, you can access most of those sections using the `getGuide` function. And from there, you can probably find the nav endpoint of any page and then call it. Some of the getX functions we have are just for convenience.

Example:
```ts
const page = await someNode.endpoint.call(yt.actions, { parse: true });
console.info(page);
```

And thanks for the PR.
