### ISSUE TITLE
Intermittent Error When Using Innertube.getHomeFeed() with Session Credentials

### ISSUE THREAD

**Issue by LArroyoS** [LuanRT/YouTube.js#802]
### Steps to reproduce

Create Innertube.

Sign in using credentials.

Attempt to fetch the home feed with innertube.getHomeFeed().

When done this way, it usually works the first few times, but as the request is repeated, it starts to fail.

Additional Information:

- I can successfully retrieve account information, but fetching the home feed fails.
- I am using the latest version of youtubei.js.
- I have verified that the credentials are correct and up-to-date.

### Failure Logs

```shell
InnertubeError: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 400
    at HTTPClient.fetch (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:2074:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Actions.execute (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:24255:22)
    at async Innertube.getHomeFeed (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:29911:22)
    at async HomeRequest (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\src\routes\home.js:44:20) {
  info: '{
    "error": {
      "code": 400,
      "message": "Request contains an invalid argument.",
      "errors": [
        {
          "message": "Request contains an invalid argument.",
          "domain": "global",
          "reason": "badRequest"
        }
      ],
      "status": "INVALID_ARGUMENT"
    }
  }',
  date: 2024-11-14T18:58:57.316Z,
  version: '11.0.1'
}
```

### Expected behavior

I expected to fetch the home feed without errors.

### Current behavior

The request fails with a 400 error indicating that the request contains an invalid argument.

### Version

Default

### Anything else?

Mi Code

```
try { 
 const innertube = await Innertube.create({ retrieve_player: false, enable_safety_mode: true, 
 generate_session_locally: false, enable_session_cache: false, device_category: "mobile", cache: new UniversalCache(false) }); 
 if (credentials) { 
  const timeout = setTimeout(() => { 
   expired = true; 
   res.status(408).json({ error: "Request Timeout" }); 
  }, 10000); 
  await innertube.session.signIn(credentials) .catch(err => { 
   console.error('Error signing in:', err); 
   expired = true; 
   res.status(500).json({ error: "Internal Server Error" }); 
   return; 
  }); 
  clearTimeout(timeout); 
 } 
 let feed = await innertube.getHomeFeed() .catch(err => { 
   console.log(err); 
   return []; 
  }); 
} 
catch (err) { 
 console.error('Error:', err); 
 return res.status(500).json({ error: "Internal Server Error"})
}
```

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by yestoall** [comment]
i have the same kind or error
Error: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 400

**Comment by babli118** [comment]
> i have the same kind or error Error: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 400

did u figure it out?

**Comment by LArroyoS** [comment]
> ### Steps to reproduce
> Create Innertube.
> 
> Sign in using credentials.
> 
> Attempt to fetch the home feed with innertube.getHomeFeed().
> 
> When done this way, it usually works the first few times, but as the request is repeated, it starts to fail.
> 
> Additional Information:
> 
> * I can successfully retrieve account information, but fetching the home feed fails.
> * I am using the latest version of youtubei.js.
> * I have verified that the credentials are correct and up-to-date.
> 
> ### Failure Logs
> ```shell
> InnertubeError: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 400
>     at HTTPClient.fetch (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:2074:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Actions.execute (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:24255:22)
>     at async Innertube.getHomeFeed (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:29911:22)
>     at async HomeRequest (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\src\routes\home.js:44:20) {
>   info: '{
>     "error": {
>       "code": 400,
>       "message": "Request contains an invalid argument.",
>       "errors": [
>         {
>           "message": "Request contains an invalid argument.",
>           "domain": "global",
>           "reason": "badRequest"
>         }
>       ],
>       "status": "INVALID_ARGUMENT"
>     }
>   }',
>   date: 2024-11-14T18:58:57.316Z,
>   version: '11.0.1'
> }
> ```
> 
> ### Expected behavior
> I expected to fetch the home feed without errors.
> 
> ### Current behavior
> The request fails with a 400 error indicating that the request contains an invalid argument.
> 
> ### Version
> Default
> 
> ### Anything else?
> Mi Code
> 
> ```
> try { 
>  const innertube = await Innertube.create({ retrieve_player: false, enable_safety_mode: true, 
>  generate_session_locally: false, enable_session_cache: false, device_category: "mobile", cache: new UniversalCache(false) }); 
>  if (credentials) { 
>   const timeout = setTimeout(() => { 
>    expired = true; 
>    res.status(408).json({ error: "Request Timeout" }); 
>   }, 10000); 
>   await innertube.session.signIn(credentials) .catch(err => { 
>    console.error('Error signing in:', err); 
>    expired = true; 
>    res.status(500).json({ error: "Internal Server Error" }); 
>    return; 
>   }); 
>   clearTimeout(timeout); 
>  } 
>  let feed = await innertube.getHomeFeed() .catch(err => { 
>    console.log(err); 
>    return []; 
>   }); 
> } 
> catch (err) { 
>  console.error('Error:', err); 
>  return res.status(500).json({ error: "Internal Server Error"})
> }
> ```
> 
> ### Checklist
> * [x]  I am running the latest version.
> * [x]  I checked the documentation and found no answer.
> * [x]  I have searched the existing issues and made sure this is not a duplicate.
> * [x]  I have provided sufficient information.

Implementing a custom authentication method, I came to the conclusion that it might be due to the limited consumption of OAuth.

To solve this, we can create a personalized OAuth, being limited to the requests that YouTube allows us, or alternatively, use cookies for the session. I have never used the latter, so I don't know how to do it. If anyone knows, I would appreciate it if you could explain how to do it.

**Comment by rizer234** [comment]
> > ### Steps to reproduce
> > Create Innertube.
> > Sign in using credentials.
> > Attempt to fetch the home feed with innertube.getHomeFeed().
> > When done this way, it usually works the first few times, but as the request is repeated, it starts to fail.
> > Additional Information:
> > 
> > * I can successfully retrieve account information, but fetching the home feed fails.
> > * I am using the latest version of youtubei.js.
> > * I have verified that the credentials are correct and up-to-date.
> > 
> > ### Failure Logs
> > ```shell
> > InnertubeError: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 400
> >     at HTTPClient.fetch (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:2074:11)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at async Actions.execute (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:24255:22)
> >     at async Innertube.getHomeFeed (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\node_modules\youtubei.js\bundle\node.cjs:29911:22)
> >     at async HomeRequest (C:\Users\W11\Documents\Leonardo\Programas\express\node-youtube\src\routes\home.js:44:20) {
> >   info: '{
> >     "error": {
> >       "code": 400,
> >       "message": "Request contains an invalid argument.",
> >       "errors": [
> >         {
> >           "message": "Request contains an invalid argument.",
> >           "domain": "global",
> >           "reason": "badRequest"
> >         }
> >       ],
> >       "status": "INVALID_ARGUMENT"
> >     }
> >   }',
> >   date: 2024-11-14T18:58:57.316Z,
> >   version: '11.0.1'
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected behavior
> > I expected to fetch the home feed without errors.
> > ### Current behavior
> > The request fails with a 400 error indicating that the request contains an invalid argument.
> > ### Version
> > Default
> > ### Anything else?
> > Mi Code
> > ```
> > try { 
> >  const innertube = await Innertube.create({ retrieve_player: false, enable_safety_mode: true, 
> >  generate_session_locally: false, enable_session_cache: false, device_category: "mobile", cache: new UniversalCache(false) }); 
> >  if (credentials) { 
> >   const timeout = setTimeout(() => { 
> >    expired = true; 
> >    res.status(408).json({ error: "Request Timeout" }); 
> >   }, 10000); 
> >   await innertube.session.signIn(credentials) .catch(err => { 
> >    console.error('Error signing in:', err); 
> >    expired = true; 
> >    res.status(500).json({ error: "Internal Server Error" }); 
> >    return; 
> >   }); 
> >   clearTimeout(timeout); 
> >  } 
> >  let feed = await innertube.getHomeFeed() .catch(err => { 
> >    console.log(err); 
> >    return []; 
> >   }); 
> > } 
> > catch (err) { 
> >  console.error('Error:', err); 
> >  return res.status(500).json({ error: "Internal Server Error"})
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Checklist
> > 
> > * [x]   I am running the latest version.
> > * [x]   I checked the documentation and found no answer.
> > * [x]   I have searched the existing issues and made sure this is not a duplicate.
> > * [x]   I have provided sufficient information.
> 
> Implementing a custom authentication method, I came to the conclusion that it might be due to the limited consumption of OAuth.
> 
> To solve this, we can create a personalized OAuth, being limited to the requests that YouTube allows us, or alternatively, use cookies for the session. I have never used the latter, so I don't know how to do it. If anyone knows, I would appreciate it if you could explain how to do it.

what cookies should i to use?

**Comment by LArroyoS** [comment]
> what cookies should i to use? please explain what are they and where should they be written?

Our friend @patrickkfkan shared this guide on how to obtain cookies.

[How to obtain Cookie](https://github.com/patrickkfkan/Volumio-YouTube.js/wiki/How-to-obtain-Cookie)

**Comment by LArroyoS** [comment]
> > what cookies should i to use? please explain what are they and where should they be written?
> 
> Our friend @patrickkfkan shared this guide on how to obtain cookies.
> 
> [How to obtain Cookie](https://github.com/patrickkfkan/Volumio-YouTube.js/wiki/How-to-obtain-Cookie)
