### ISSUE TITLE
Formato de áudio não encontrado

### ISSUE THREAD

**Issue by tonykx** [LuanRT/YouTube.js#804]
### Steps to reproduce

case 'playyy': {
    if (args.length < 1) return reply("Insira o comando, e em seguida um nome para a pesquisa!");

    const { Innertube } = require('youtubei.js');
    const fetch = (await import("node-fetch")).default;
    const fs = require('fs');

    // Criação da instância do Innertube com cookies
    const cookie = 'seu_cookie_aqui'; // Substitua pelo cookie adequado
    const youtube = await Innertube.create({ cookie });

    try {
        // Realiza a pesquisa diretamente
        const searchResults = await youtube.search(args.join(" "));
        const firstResult = searchResults.results[0];
        
        if (!firstResult) {
            return reply("Nenhum vídeo encontrado.");
        }

        const videoId = firstResult.id;
        const videoInfo = await youtube.getBasicInfo(videoId);
        const audioFormat = videoInfo.streaming_data?.formats[0]; 
        
        if (!audioFormat) {
            return reply("Formato de áudio não encontrado.");
        }

        const audioUrl = audioFormat.decipher(youtube.session.player);
        const vidName = `audio_${Date.now()}.mp3`;
        const path = `Del/${vidName}`;
        const writer = fs.createWriteStream(path);

        const audioStream = await fetch(audioUrl);
        
        if (!audioStream.ok) {
            throw new Error(`Erro ao baixar áudio: ${audioStream.statusText}`);
        }
        
        audioStream.body.pipe(writer);

        writer.on("finish", async () => {
            console.log("Download Completo!");
            await conn.sendMessage(from, { audio: { url: path }, mimetype: "audio/mpeg" }, { quoted: info });
            fs.unlink(path, (err) => {
                if (err) console.error("Erro ao deletar o arquivo:", err);
            });
        });

    } catch (error) {
        console.error("Erro durante o processo:", error);
        reply("Ocorreu um erro ao tentar reproduzir o áudio.");
    }

    break;
}

### Failure Logs

```shell
[YOUTUBEJS][Text]: Unable to find matching run for command run. Skipping... {
  command_run: { startIndex: 0, length: 54, onTap: { innertubeCommand: [Object] } },
  input_data: {
    content: 'Maria Marçal - Deixa (Clipe Oficial MK Music) · 4:20',
    commandRuns: [ [Object] ]
  },
  parsed_runs: [
    {
      text: 'Maria Marçal - Deixa (Clipe Oficial MK Music) · 4:20',
      startIndex: 0
    }
  ]
}
[YOUTUBEJS][Text]: Unable to find matching run for command run. Skipping... {
  command_run: { startIndex: 0, length: 55, onTap: { innertubeCommand: [Object] } },
  input_data: {
    content: 'Valesca Mayssa | Eu Sou Teu Pai [Clipe Oficial] · 6:32',
    commandRuns: [ [Object] ]
  },
  parsed_runs: [
    {
      text: 'Valesca Mayssa | Eu Sou Teu Pai [Clipe Oficial] · 6:32',
      startIndex: 0
    }
  ]
}
```

### Expected behavior

Não obtenho o download do áudio 

### Current behavior

Formato de áudio não encontrado 

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by tonykx** [comment]
@LuanRT , algo que posso fazer?

**Comment by patrickkfkan** [comment]
[IStreamingData](https://github.com/LuanRT/YouTube.js/blob/bdebb9f741291d2f0640274454c90b5ccda8ea5d/docs/api/namespaces/APIResponseTypes/interfaces/IStreamingData.md) has `adaptive_formats` in addition to `formats`.
