### ISSUE TITLE
InnertubeError: PlaylistHeader not found!

### ISSUE THREAD

**Issue by speechless42** [LuanRT/YouTube.js#81]
const Innertube = require('youtubei.js');
var playlist1 = [];
  async function start1() {
    const youtube = await new Innertube();
    playlist1[0] = await youtube.getPlaylist("PL4fGSI1pDJn4-UIb6RKHdxam-oAUULIGB");
    console.log(playlist1[0])
  }
**And i run it come out !! Need login? Thanks to answer me**
![image](https://user-images.githubusercontent.com/94534629/175356685-0ea94462-20c1-4e1c-8ed6-896a34d8e6b7.png)

**Comment by LuanRT** [comment]
Thank you for your report, that's just a missing renderer and will be fixed soon.
If you do `console.log(playlist1[0].videos)` and it prints all the videos then you don't have to worry about it for now.

**Comment by speechless42** [comment]
Thank you
