### ISSUE TITLE
Por favor, como faço pra resolver esse problema

### ISSUE THREAD

**Issue by tonykx** [LuanRT/YouTube.js#820]
### Steps to reproduce

https://www.youtube.com/youtubei/v1/player?prettyPrint=false&alt=json

### Failure Logs

```shell
,
```

### Expected behavior

Obter áudio 

### Current behavior

Falha

### Version

Edge

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
You have four options:
1. Sign in. Either using cookies or OAuth (although you'll be limited to the TV client, but that's fine if all you want is the streaming data).
2. Use the iOS client, but logged out. 
3. Use the WEB client. You'll need PoTokens. 
4. Use Onesie requests. This is an advanced topic and more complicated than the other options. See https://github.com/LuanRT/googlevideo for more info. 

Next time please use English so that others can understand and potentially help you.

**Comment by tonykx** [comment]
Como posso adaptar esse código aqui para o uso de cookies:

case 'vid': {
    if (!args.length) return reply("Insira o comando, e em seguida um nome para a pesquisa!");

    try {
        const searchResults = await yts(args.join(" "));
        const firstResult = searchResults.all.find(result => result?.videoId);
        if (!firstResult) {
            return reply("Nenhum resultado válido encontrado para a sua pesquisa.");
        }

        const { videoId, title, timestamp, thumbnail } = firstResult;
        
        const caption = `🎥 Título: ${title}\n⌛ Duração: ${timestamp}`;
        const imageOptions = { url: thumbnail };
        await conn.sendMessage(from, { image: imageOptions, caption: caption }, { quoted: info });
        
        // Obter informações completas do vídeo usando OAuth2
        const videoInfo = await ytdl.getFullInfo(`https://www.youtube.com/watch?v=${videoId}`, {
            oauth2: new ytdl.OAuth2({
                accessToken: accessToken,
                refreshToken: refreshToken,
                expiryDate: expiryDate,
            }),
        });
        
        // Baixar o vídeo com qualidade média
        const stream = ytdl.downloadFromInfo(videoInfo, {
            filter: "videoandaudio", // Baixar tanto vídeo quanto áudio
            quality: 'lowest' // Pode ajustar para qualidade melhor, se preferir
        });

        const filePath = `Del/${await getRandom('.mp4')}`;
        
        // Função para gerenciar o download do vídeo
        const downloadVideo = (stream, filePath) => {
            return new Promise((resolve, reject) => {
                const writer = fs.createWriteStream(filePath);
                stream.pipe(writer);
                writer.on("finish", () => {
                    writer.close();
                    resolve();
                });
                writer.on("error", reject);
            });
        };

        await downloadVideo(stream, filePath);
        console.log("Download Completo!");

        // Enviar o vídeo
        await conn.sendMessage(from, { video: { url: filePath }, caption: caption }, { quoted: info });
        fs.unlinkSync(filePath);

    } catch (error) {
        console.error("Ocorreu um erro:", error);
        reply("Ocorreu um erro ao processar sua solicitação.");
    }
    break;
}
