### ISSUE TITLE
Issues with Custom Authentication in YouTube.js: Error invalid_scope

### ISSUE THREAD

**Issue by LArroyoS** [LuanRT/YouTube.js#824]
### Question

Hello everyone,

Has anyone had problems recently with custom authentication in YouTube.js?

Since yesterday, I have been receiving the following error message:

Some requested scopes cannot be shown: [https://www.googleapis.com/auth/accounts.reauth]

My code is almost the same as the example provided in YouTube.js:

[Custom OAuth2 Credentials Example in YouTube.js](https://github.com/LuanRT/YouTube.js/blob/main/examples/auth/custom-oauth2-creds/index.ts)

I would appreciate any help or suggestions to resolve this issue.

Thank you!

### Other details

My Code

```
const OauthRequest = async (req, res) => {
    try{
        const oAuth2Client = new OAuth2Client(
            clientid,
            clientsecret,
            redirectUri
        );

        const authorizationUrl = oAuth2Client.generateAuthUrl({
            access_type: 'offline',
            scope: [
                "http://gdata.youtube.com",
                "https://www.googleapis.com/auth/youtube",
                "https://www.googleapis.com/auth/youtube.force-ssl",
                "https://www.googleapis.com/auth/youtube-paid-content",
                "https://www.googleapis.com/auth/accounts.reauth",
            ],
            include_granted_scopes: true,
            prompt: 'consent',
            state: code
        });

        return res.redirect(authorizationUrl);
    }
    catch (err) { 
        console.error("Error ", err)
        return res.redirect(`/auth?error=Internal Server Error`);
    }
}
```

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by farhaanaliii** [comment]
I am getting these, : (
![image](https://github.com/user-attachments/assets/e4d73ea3-c809-4cae-9bea-b7074c58c9d6)

**Comment by hostyn** [comment]
I had the same error as you today and fixed it by removing the line `include_granted_scopes: true`. It seems that this parameter conflicts with the scope `https://www.googleapis.com/auth/accounts.reauth`.

**Comment by LArroyoS** [comment]
> > I had the same error as you today and fixed it by removing the line `include_granted_scopes: true`. It seems that this parameter conflicts with the scope `https://www.googleapis.com/auth/accounts.reauth`.
> 
> Indeed, removing the line include_granted_scopes: true made the application work again.
> 
> It helped me a lot.
> 
> Thank you very much.
