### ISSUE TITLE
[YOUTUBEJS][Player]: Failed to extract signature decipher algorithm.

### ISSUE THREAD

**Issue by PingHead2** [LuanRT/YouTube.js#831]
### Steps to reproduce

I am currently getting the following error:

[YOUTUBEJS][Player]: Failed to extract signature decipher algorithm.

YouTube, based on YT-DLP and other projects, has updated the signature extraction process. I believe the current signature extraction method is outdated, which is causing this issue.

### Failure Logs

```shell
[YOUTUBEJS][Player]: Failed to extract signature decipher algorithm.
```

### Expected behavior

actually extract it

### Current behavior

not extracting it

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by MaiTN01** [comment]
Same issue

**Comment by qinfendezhou** [comment]
Same issue

**Comment by omerman** [comment]
same issue

**Comment by songgnqing** [comment]
```js
if (typeof uwg === "undefined")
    return J;
```
The nsig algorithm needs to be handled here, otherwise it will return the same value as the argument

**Comment by LuanRT** [comment]
> ```js
> if (typeof uwg === "undefined")
>     return J;
> ```
> 
> The nsig algorithm needs to be handled here, otherwise it will return the same value as the argument

Jinter does not handle `undefined` vars the same way browsers and other JS engines do (I didn't bother implementing it the proper way). So we don't have to do anything about that because `typeof uwg === "undefined"`  will always return `false`. In Jinter, `uwg` is literally `"uwg"`, if that makes any sense.

**Comment by twicer-is-coder** [comment]
This is happening again now since 24 March. I am using v13.2.0.

**Comment by omerman** [comment]
Having the same issue

**Comment by sgebr01** [comment]
Same, I'm just now getting this issue.

**Comment by yousseftarhri** [comment]
Same issue version 13.3.0
