### ISSUE TITLE
v12.2.0 ParsingError: Expected node of any type AddChatItemAction, got RunAttestationCommand

### ISSUE THREAD

**Issue by ernbaltaci** [LuanRT/YouTube.js#853]
### Steps to reproduce

I have youtube live chat bot and when I was try sending message I taking error. 

My message message length less than 200. 

### Failure Logs

```shell
ParsingError: Expected node of any type AddChatItemAction, got RunAttestationCommand
    at /Users/x/Desktop/x/x/x/x/node_modules/youtubei.js/bundle/node.cjs:435:19
    at Array.map (<anonymous>)
    at Proxy.<anonymous> (/Users/x/x/x/x/x/node_modules/youtubei.js/bundle/node.cjs:432:33)
    at LiveChat2.sendMessage (/Users/x/x/x/x/x/node_modules/youtubei.js/bundle/node.cjs:16815:37)
    at processTicksAndRejections (node:internal/process/task_queues:105:5) {
  date: 2024-12-21T15:14:42.851Z,
  version: '12.2.0'
}
```

### Expected behavior

I was expecting not to get any errors when sending messages.

### Current behavior

While sending a message, I get the error `ParsingError: Expected node of any type AddChatItemAction, got RunAttestationCommand`

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [x] I have provided sufficient information.

**Comment by groboclone** [comment]
Experiencing the exact same error here. The message does then send, after a long delay (around 7 seconds).
