### ISSUE TITLE
Using this with Node.JS 12

### ISSUE THREAD

**Issue by sgebr01** [LuanRT/YouTube.js#86]
### Question

Hi, I'm trying to use this for a webOS app(which currently supports Node v12.1). I was wondering if it is possible at all to use this with node.js 12 at all. Is there an older version of this library that I could use that supports it? 

### Other details

For WebOS
Currently supports Node.JS 12.14.1

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
> I was wondering if it is possible at all to use this with node.js 12 at all. Is there an older version of this library that I could use that supports it?

That would be version 1.0.5 ~ 1.2.0. However, you would lose so many features that it might not be worth it at all. I think all that stops this library from working in Node 12 is the use of private fields, if you could somehow get rid of them it would probably work.

**Comment by LuanRT** [comment]
Hey if you still need this, Node.Js 12 is now supported.
