### ISSUE TITLE
Best way to determine if an item will be playable with YTM?

### ISSUE THREAD

**Issue by polds** [LuanRT/YouTube.js#89]
### Question

I'm wondering if there is a solid way if it's possible, given a single Video Id, to determine if that video/song will be playable within YouTube Music.

For example, given the Video Id: [t5YjeAYnD8c](https://youtu.be/t5YjeAYnD8c) if you call `youtube.getDetails('t5YjeAYnD8c')` you get some results that show the item has category "Music", is not unlisted, available in my country (US), and everything else that shows that it might be available in YouTube Music. But if you try to load it, it says it's unavailable. (Is it a quality thing? 480p is the highest available for that particular song?)

I could try `youtube.search('title', { client: "YTMUSIC" })` but I've found that can be difficult to match up the exact title to song.

I've also stumbled on a few songs that do not have a Music category, but are playable within YouTube Music.

So I'm wondering if there's a good way to determine if a given video will be playable within YTM.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
There's no official way to do that in v1.4.3. But if you switch to the dev version you can try this:
```js
const payload = {
  videoId: 't5YjeAYnD8c',
  client: 'YTMUSIC'
};
  
const info = await youtube.actions.execute('/player', payload);
console.info(info.data.playabilityStatus);
```
Which outputs:
```js
{
  status: 'UNPLAYABLE',  
  reason: 'This video is not available'
}

**Comment by polds** [comment]
This is great! I confirmed several of my suspected "MUSIC" yet unplayable within YTM and using the dev version correctly identified all of them as UNPLAYABLE.
