### ISSUE TITLE
How To fix This!!!? 

### ISSUE THREAD

**Issue by ThisMe124** [LuanRT/YouTube.js#9]
How Fix This? 

![PLEASE HELP ME!!](https://user-images.githubusercontent.com/88891071/149739384-4859aa7a-707b-4006-a477-c6b6c0d247af.jpg)

**Comment by LuanRT** [comment]
Hello,

That's due to YouTube no longer providing the dislike count, it's already been fixed but I haven't published the new version to NPM yet (will do it soon). 

If you still need the livechat functionality you can either wait until the new version is published to NPM or just add the YouTube.js repo to your package.json dependencies:

```js
{
  "dependencies": {
    "youtubei.js": "git+https://github.com/LuanRT/YouTube.js"
    //...
  }
}
```

**Comment by ThisMe124** [comment]
Oh okay Thnks

**Comment by ThisMe124** [comment]
> Hello,
> 
> That's due to YouTube no longer providing the dislike count, it's already been fixed but I haven't published the new version to NPM yet (will do it soon).
> 
> If you still need the livechat functionality you can either wait until the new version is published to NPM or just add the YouTube.js repo to your package.json dependencies:
> 
> ```js
> {
>   "dependencies": {
>     "youtubei.js": "git+https://github.com/LuanRT/YouTube.js"
>     //...
>   }
> }
> ```

It's the same, the error is the same even though I've replaced it with the Github repo

**Comment by ThisMe124** [comment]
![IMG_20220118_203755](https://user-images.githubusercontent.com/88891071/149938797-8c14181b-4c25-4f1f-9ae6-b0822f9a5879.jpg)
HMMMM😶🤔

**Comment by ThisMe124** [comment]
> > Hello,
> > That's due to YouTube no longer providing the dislike count, it's already been fixed but I haven't published the new version to NPM yet (will do it soon).
> > If you still need the livechat functionality you can either wait until the new version is published to NPM or just add the YouTube.js repo to your package.json dependencies:
> > ```js
> > {
> >   "dependencies": {
> >     "youtubei.js": "git+https://github.com/LuanRT/YouTube.js"
> >     //...
> >   }
> > }
> > ```
> 
> It's the same, the error is the same even though I've replaced it with the Github repo

**And More Errors...**
![IMG_20220118_204517](https://user-images.githubusercontent.com/88891071/149939910-d1a475ed-7b40-449a-ad13-d29aa4dc296a.jpg)

**Comment by LuanRT** [comment]
> > > Hello,
> > > That's due to YouTube no longer providing the dislike count, it's already been fixed but I haven't published the new version to NPM yet (will do it soon).
> > > If you still need the livechat functionality you can either wait until the new version is published to NPM or just add the YouTube.js repo to your package.json dependencies:
> > > ```js
> > > {
> > >   "dependencies": {
> > >     "youtubei.js": "git+https://github.com/LuanRT/YouTube.js"
> > >     //...
> > >   }
> > > }
> > > ```
> > 
> > 
> > It's the same, the error is the same even though I've replaced it with the Github repo
> 
> **And More Errors...** ![IMG_20220118_204517](https://user-images.githubusercontent.com/88891071/149939910-d1a475ed-7b40-449a-ad13-d29aa4dc296a.jpg)

You are getting errors at the initialization stage? I've made some tests and everything seems to be alright. What version of NodeJs are you using?

**Comment by ThisMe124** [comment]
I am using nodejs  v12.22.6.

**Comment by ThisMe124** [comment]
And I Am Updates to nodejs v16 version

**Error Likes This**
![IMG_20220119_141240](https://user-images.githubusercontent.com/88891071/150074436-85aaa392-fbd8-4ace-81ef-23440312ed11.jpg)

**Comment by ThisMe124** [comment]
Has Been Fixed Thanks For Support :)
