### ISSUE TITLE
Upload youtube video

### ISSUE THREAD

**Issue by naptestdev** [LuanRT/YouTube.js#94]
### Describe your suggestion

According to Youtube Data API v3
<img width="841" alt="image" src="https://user-images.githubusercontent.com/88878684/178101160-b0b54219-28ef-40d1-b7bd-851f3e859de9.png">

So it should be great if you can use to internal Innertube API to allow uploading videos without the restriction.

Thanks a lot.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
JFYI I found out the upload endpoints used by YouTube Studio require the browser to solve a botguard challenge,  which is out of scope for this project. On the bright side of things, however, the Android app ones seem to be free of any hurdles so we'll probably use that.

**Comment by LuanRT** [comment]
A little update:
See #115
