### ISSUE TITLE
getComments will throw out an error when the comment count of the video is 0

### ISSUE THREAD

**Issue by SuiKaSan** [LuanRT/YouTube.js#95]
### Steps to reproduce

Example:
1.find a video that with no coment( for example: Ja2H4xHnX-0 )
2.take its video id and invoke getComents function

### Failure Logs

```shell
(node:17108) UnhandledPromiseRejectionWarning: Error: Expected to find "onResponseReceivedEndpoints" with content "commentRenderer" but got undefined
    at Object.findNode (D:\code\demo\youtubeReptile\node_modules\youtubei.js\lib\utils\Utils.js:39:22)
    at parseComments (D:\code\demo\youtubeReptile\node_modules\youtubei.js\lib\parser\index.js:281:27)
    at Parser.#processComments (D:\code\demo\youtubeReptile\node_modules\youtubei.js\lib\parser\index.js:351:12)
    at Object.COMMENTS (D:\code\demo\youtubeReptile\node_modules\youtubei.js\lib\parser\index.js:33:48)
    at Parser.parse (D:\code\demo\youtubeReptile\node_modules\youtubei.js\lib\parser\index.js:37:22)
    at Innertube.getComments (D:\code\demo\youtubeReptile\node_modules\youtubei.js\lib\Innertube.js:239:8)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected behavior

return normal response with 0 comment count.

### Current behavior

throw out an error when the comment count of the video is 0

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hey, thanks for your report.
I believe this has already been fixed in the dev version. See #65, you can try it if you have time.

**Comment by SuiKaSan** [comment]
> Hey, thanks for your report. I believe this has already been fixed in the dev version. See #65, you can try it if you have time.
> 
> Edit: And do note that the structure of the response in the dev version is a bit different, but also much better. You can find examples [here](https://github.com/LuanRT/YouTube.js/tree/main/examples/comments).



> Hey, thanks for your report. I believe this has already been fixed in the dev version. See #65, you can try it if you have time.
> 
> Edit: And do note that the structure of the response in the dev version is a bit different, but also much better. You can find examples [here](https://github.com/LuanRT/YouTube.js/tree/main/examples/comments).

I changed to the new version. But it didn't work.

**Comment by SuiKaSan** [comment]
![image](https://user-images.githubusercontent.com/44567811/178390766-fa5d200f-d6fc-4ade-9d54-d5fe7d0d9971.png)
![image](https://user-images.githubusercontent.com/44567811/178390766-fa5d200f-d6fc-4ade-9d54-d5fe7d0d9971.png)

**Comment by SuiKaSan** [comment]
I get into youtubei.js/node_modules and run npm install. The function works fine now.
But when I use **getInfo** function , another error comes.
![image](https://user-images.githubusercontent.com/44567811/178404999-50821e7c-a5b5-441b-9ae9-793df3821650.png)

**Comment by LuanRT** [comment]
> ![image](https://user-images.githubusercontent.com/44567811/178390766-fa5d200f-d6fc-4ade-9d54-d5fe7d0d9971.png)

Sorry about that, I forgot to mark all dependencies as external in the build command. Should be fixed now (d1f2369e43bb8a78cfadef0a25798846113ba351).

**Comment by LuanRT** [comment]
> I get into youtubei.js/node_modules and run npm install. The function works fine now. But when I use **getInfo** function , another error comes. ![image](https://user-images.githubusercontent.com/44567811/178404999-50821e7c-a5b5-441b-9ae9-793df3821650.png)

Don't worry about that, it's just a silent error and doesn't crash/change anything in the results, it's there just to tell you that there is something missing and it should be reported. Anyhow, thank you.

**Comment by SuiKaSan** [comment]
I use the newest version. The one with your dependencies repaired.
But pops out a new error.
![image](https://user-images.githubusercontent.com/44567811/178451835-c6c9dc9a-f830-4d72-9562-2c251d3bc077.png)

**Comment by SuiKaSan** [comment]
@LuanRT Can you please check this problem?

**Comment by LuanRT** [comment]
> @LuanRT Can you please check this problem?

Hi there, it's likely a network error. I haven't changed anything related to that in the latest commits so it might be something else. You can try using the debug parameter (`...Innertube({ debug: true })`) and see how far the library is able to make requests.

**Comment by SuiKaSan** [comment]
Problem above network problem, sorry about that,
But when I fixed the problem, another bug pops.
I'm pretty sure is not network issue.
I already intall the lastest version.
Can you tell me how to fix it? Thanks. @LuanRT 
![image](https://user-images.githubusercontent.com/44567811/179137348-f1197bc2-9d81-4f53-831a-18ecc685c40c.png)
