### ISSUE TITLE
Suggestion: Discord server?

### ISSUE THREAD

**Issue by Wykerd** [LuanRT/YouTube.js#96]
It would be nice if we could have a Discord server to discuss the library, ask questions and discuss upcoming changes.

**Comment by LuanRT** [comment]
I'm down for it, but unfortunately I have little to no experience in property setting up a Discord Server — so if any of you guys do then we can have it.

**Comment by Wykerd** [comment]
I can set it up if you want me to?

**Comment by LuanRT** [comment]
> I can set it up if you want me to?

Sure, if you're willing to, then that'd be great.

**Comment by Wykerd** [comment]
I'm also no expert at this but here's the link https://discord.gg/syDu7Yks54

**Comment by LuanRT** [comment]
Nice, I'll join in a min. Also, should probably have an issue with the link pinned.

**Comment by Wykerd** [comment]
Could probably be added to the README too?
